### ISSUE TITLE
Bug: game_text crashes the game when using Panorama UI

### ISSUE THREAD

**Issue by Doclic** [StrataSource/Portal-2-Community-Edition#1009]
### Describe the bug

[The `game_text` entity](https://developer.valvesoftware.com/wiki/Game_text) freezes/crashes the game when the text fades out when using Panorama.
It also uses the wrong font, as mentioned in #980.

### To Reproduce

1. Create a map with a `game_text` entity that's triggered
2. Go to the trigger

### Operating System

Tested using Linux (Pop!_OS)

**Comment by Doclic** [comment]
[This was also mentioned in the Chaos Source issue tracker a year ago](https://github.com/ChaosInitiative/Chaos-Source/issues/248), but at the time no text showed up, now it crashes the game.

**Comment by Luke18033** [comment]
For me, it doesn't crash and the text still doesn't appear

**Comment by Doclic** [comment]
> For me, it doesn't crash and the text still doesn't appear

It works as expected for me now, both in default, nightly, and previous_version
![image](https://user-images.githubusercontent.com/30270428/233952192-7e5f01e2-84c8-439e-89f6-5327787e568e.png)

Map (gzipped so that I can upload it on GH)
[text.bsp.gz](https://github.com/StrataSource/Portal-2-Community-Edition/files/11308675/text.bsp.gz)
[text.vmf.gz](https://github.com/StrataSource/Portal-2-Community-Edition/files/11308682/text.vmf.gz)

**Comment by Luke18033** [comment]
Which text channel are you using, I wonder if the text not appearing is specific to the small/big text sizes used by channels 2 and 3

**Comment by Doclic** [comment]
> Which text channel are you using, I wonder if the text not appearing is specific to the small/big text sizes used by channels 2 and 3

The original map was using channel 1.
I tried channels 1-4, and 2 & 3 don't work for me either.

Should I make another issue and close this one?

**Comment by Luke18033** [comment]
Yeah probably

**Comment by Doclic** [comment]
It's being tracked at #1298
