### ISSUE TITLE
Bug: CO-OP VGUI pause menu doesn't show up.

### ISSUE THREAD

**Issue by Trico-Everfire** [StrataSource/Portal-2-Community-Edition#1010]
### Describe the bug

the VGUI coop pause menu doesn't show up when you try and pause the game.

### Issue Map

map mp_coop_community_hub

### To Reproduce

go into mp_coop_community_hub
try and press esc (aka the pause menu)
doesn't work.

### Operating System

Linux

**Comment by Luke18033** [comment]
Seems fixed
