### ISSUE TITLE
Bug: Crash to desktop when applying handbrake on prop_vehicle_jeep with EP2 Jalopy vehicle script applied

### ISSUE THREAD

**Issue by pivotman319-owo** [StrataSource/Portal-2-Community-Edition#1033]
### Describe the bug

Attempting to apply the handbrake while inside of a prop_vehicle_jeep with the jalopy.txt vehicle script when driving with enough velocity will cause a crash within the Havok physics engine. This issue is not reproducible with a prop_vehicle_jeep that has the default HL2 jeep vehicle script.

This issue is also present in the standard Source SDK 2013 codebase.

### Issue Map

N/A

### To Reproduce

1. Open any map
2. `ch_createjalopy`
3. Enter the jalopy, drive at a high enough velocity and apply brakes

Reproduction video:
https://user-images.githubusercontent.com/15126754/190852791-d702c8e7-6435-48da-9f11-341b60fc0dd4.mp4

**Comment by JJL772** [comment]
Is this still an issue?
