### ISSUE TITLE
Citizen with portalgun crashes the game

### ISSUE THREAD

**Issue by vrad-exe** [StrataSource/Portal-2-Community-Edition#1088]
### Describe the bug

Spawning an `npc_citizen` holding a `weapon_portalgun` crashes the game

### Issue Map

[bug_citizen_portalgun.zip](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/10263241/bug_citizen_portalgun.zip)

### To Reproduce

1. Open attached map
2. Game crashes

### Operating System

Tested on Windows 10

**Comment by pivotman319-owo** [comment]
related to nonexistent viewmodel

**Comment by Luke18033** [comment]
Should probably just make it behave the same as an in-world portalgun when being carried by an NPC

**Comment by Gocnak** [comment]
Should be fixed in the next version
