### ISSUE TITLE
Jittery multiplayer movement as host

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1104]
### Describe the bug

When loading into a multiplayer game as the host, the player's movement is jittery. This only occurs when `cl_predict` is turned off (which is the default for the host, including in P2). For joining clients, turning off prediction behaves as expected.

In Portal 2, the host's movement is smooth like in singleplayer

### Issue Map

Any

### To Reproduce

1. Load any map in a multiplayer listen server
2. Host's movement is jittery

### Operating System

Tested on Windows 10

**Comment by Luke18033** [comment]
Even with prediction enabled movement still seems to behave weirdly for the host, sometimes there will be random 1-frame motion blur bursts which don't seem to ever appear for joining clients

**Comment by ozxybox** [comment]
Is this still an issue?

**Comment by ozxybox** [comment]
Agh, github said this was opened "last year". Turns out "last year" means "Jan 11th of THIS year".
Thanks github! Likely still an issue then...

**Comment by Luke18033** [comment]
Fixed
