### ISSUE TITLE
Bug: NPC controlled by scripted_sequence is killed upon firing CancelSequence input

### ISSUE THREAD

**Issue by VirgilCore** [StrataSource/Portal-2-Community-Edition#1111]
### Describe the bug

When a scripted_sequence point entity is controlling an NPC, and it receives the "CancelSequence" input, the NPC will instantly die. Expected result would be the NPC returning to AI

### Issue Map

Any

### To Reproduce

1. Make a scripted_sequence
2. Create an NPC to control 
3. Make the sequence run on map start (through a trigger or a logic auto)
4. Fire the scripted_sequence to CancelSequence

**Comment by pivotman319-owo** [comment]
@VirgilCore please provide a sample issue map for this, I'm unable to repro this edge case

https://user-images.githubusercontent.com/15126754/212419440-e2b8ee1d-f310-4879-953c-d6a6c473e8cd.mp4

**Comment by VirgilCore** [comment]
I will send a sample map when i get home

**Comment by pivotman319-owo** [comment]
@VirgilCore is there an update on this?

**Comment by pivotman319-owo** [comment]
Closing this for now unless we can actually get a working sample repro map here.
