### ISSUE TITLE
Bug: Failed to load library engine.so: libbz2.so.1.0: No such file or directory

### ISSUE THREAD

**Issue by betaRadiation** [StrataSource/Portal-2-Community-Edition#1122]
### Describe the bug

When I open the game it spits out this error: 

Failed to load library /home/****/.local/share/Steam/steamapps/common/Portal 2 Community Edition/bin/linux64/engine.so: libbz2.so.1.0: cannot open shared object file: No such file or directory

![image](https://user-images.githubusercontent.com/67484484/215298195-4fa22ca4-7dea-4130-a623-92ed57bd6c68.png)

### Issue Map

N/A

### To Reproduce

1. Open the game
2. Crash

### Operating System

Fedora Linux 36

**Comment by JJL772** [comment]
Make sure you install the libbz2 package your distro provides, or install ffmpeg, which should provide that package (libbz2 is a dependency of libavformat which should come from ffmpeg)

**Comment by betaRadiation** [comment]
I have libbz2 installed


❯ dnf list installed "*bz*"
Installed Packages
bzip2.x86_64                                                     1.0.8-11.fc36                                    @fedora 
bzip2-devel.x86_64                                               1.0.8-11.fc36                                    @fedora 
bzip2-libs.i686                                                  1.0.8-11.fc36                                    @fedora 
bzip2-libs.x86_64                                                1.0.8-11.fc36                                    @fedora

**Comment by betaRadiation** [comment]
oops i closed it

**Comment by JJL772** [comment]
Hmm, is `libbz2.so.1.0` in `/usr/lib64/` or `/usr/lib/x86_64-linux-gnu`? (Not sure which dir fedora uses)

Also, are you using normal steam or flatpak steam?

Try running this in the steam linux runtime, maybe it'll work there.

**Comment by betaRadiation** [comment]
There is no libbz2.so.1.0 but libbz.so.1.0.8,  libbz.so.1, libbz.so exist in `/usr/lib64`

Im running normal steam.

p2ce works with steam linux runtime.

**Comment by JJL772** [comment]
Alright, I'd just keep using the steam linux runtime then. We'll fix the library issues though, thanks for the report!

**Comment by ozxybox** [comment]
Closing this issue, as I believe we've improved the Linux dependency situation since January.
