### ISSUE TITLE
sv_force_enable_paint needs FCVAR_REPLICATED

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1128]
### Describe the bug

If `sv_force_enable_paint` is used in multiplayer, paint will be invisible for players other than the host. In maps with paint enabled normally, this works correctly

Having clients set the cvar themselves usually fixes the problem, so it probably just needs to be `replicated`.

### Issue Map

Any

### To Reproduce

1. Enable `sv_force_enable_paint` and load map without gel in multiplayer mode
2. Run a second instance of the game and have a player join
3. They can't see any gel that's placed

### Operating System

All players on Windows 10

**Comment by JJL772** [comment]
Done in latest
