### ISSUE TITLE
Bug: Connection to game server failed.

### ISSUE THREAD

**Issue by kekuyer** [StrataSource/Portal-2-Community-Edition#1129]
### Describe the bug

when i try to load any map, this error appears. You can fix it if you will try to load the map again, but its pretty annoying.
![image](https://user-images.githubusercontent.com/94962984/215324087-6fcb5236-a491-4466-8837-85cd9a62a757.png)

### Issue Map

every map

### To Reproduce

1. Start the game.
2. Try to load any map from main menu (could be a map command in console, or a chapter selection in new game menu)

**Comment by ozxybox** [comment]
I believe this issue was fixed, but if it is still happening for you, please feel free to reopen it.
