### ISSUE TITLE
Bug: Failed to load library panorama.so: libcairo.so: No such file or directory

### ISSUE THREAD

**Issue by betaRadiation** [StrataSource/Portal-2-Community-Edition#1132]
### Describe the bug

When launching the panorama UI beta the game spits out error `Falled to load library /home/****/.local/share/Steam/steamapps/common/Portal 2 Community Edition/bin/linux64/panorama.so: libcairo.so: cannot open shared object file: No such file or directory` and crashes. I can fix this problem by coping "libcairo_client.so" from a cs:go installation into the linux64 folder of p2ce and renaming it to "libcairo.so". When doing this fix I run into another error `Unable to load libpangoft2-1.0.so (error info libpng12.so.0: cannot open shared object file: No such file or directory), your game install may be corrupted or you may have a system conflict`. The game runs fine with legacy UI.

![image](https://user-images.githubusercontent.com/67484484/215355621-af309bd3-e87b-4242-99af-bb7075337cda.png)

![Screenshot_20230129_145331](https://user-images.githubusercontent.com/67484484/215355547-3c876e62-7883-489d-81eb-00da3ed6e0c6.png)

### Issue Map

N/A

### To Reproduce

1. Open the game with panorama UI
2. Crash
3. Do the cs:go file coping fix
4. Get libpangoft2-1.0.so error
5. Crash

### Operating System

Fedora Linux 36 (running game using Steam Linux Runtime)

**Comment by ozxybox** [comment]
Closing, as this is a 2 year old issue, and I haven't heard of similar issues since
