### ISSUE TITLE
Film grain overlay visible at all times

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1133]
### Describe the bug

At all times while in-game in the latest versions of P2CE, a subtle film grain overlay (presumably from L4D) is visible.
![image](https://user-images.githubusercontent.com/19228201/215362048-44833e9e-606c-4909-901b-684ecf01ad4a.png)

### Issue Map

Any

### To Reproduce

1. Open map
2. Look closely at the screen (easiest to see when it's dark)
3. There is a film grain overlay

### Operating System

Tested on Windows 10

**Comment by Luke18033** [comment]
In multiplayer, it seems to only appear to the host on a listen server

**Comment by ozxybox** [comment]
Is this still an issue? I think this was solved?

**Comment by tmob03** [comment]
> Is this still an issue? I think this was solved?

It is indeed fixed
