### ISSUE TITLE
"Connection Problem" message doesn't appear

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1144]
### Describe the bug

When the connection to a server is lost, the `WARNING: Connection Problem, Auto-disconnect in x seconds` message does not appear in the top-right corner of the screen, despite the server timeout still occurring.

### Issue Map

Any

### To Reproduce

1. Start a listen server
2. Have a second client connect
3. Crash the first client (e.g. with the `crash` command)
4. "Connection Problem" does not appear, but you still disconnect after 30 seconds

### Operating System

Tested on Windows 10

**Comment by ozxybox** [comment]
This was fixed on the staging branch.
