### ISSUE TITLE
Viewmodel grabbing in noclip

### ISSUE THREAD

**Issue by vrad-exe** [StrataSource/Portal-2-Community-Edition#1151]
### Which component should be improved?

Gameplay

### Describe your suggestion

When `player_held_object_use_view_model` is set to -1 (the default value), objects should be forced to use viewmodel grabbing if the player carrying the object is noclipping. This allows objects to be carried through walls.

Could make this controlled by a second cvar `noclip_grab_use_vm` or the like

**Comment by ozxybox** [comment]
Fixed by @craftablescience in the next staging build
