### ISSUE TITLE
Allow disabling Portal 2 ClientCommands

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1153]
### Which component should be improved?

Other

### Describe your suggestion

Portal 2 contains a number of [ClientCommands](https://developer.valvesoftware.com/wiki/ClientCommand) that are highly problematic for dedicated servers. These commands can be executed by *any connected client*, allowing them to change the map that the server is running or do other disruptive things.
- `pre_go_to_hub` / `pre_go_to_calibration` - displays Coop loading videos over every player's screen
- `go_to_hub` / `go_to_calibration` - changes level to the hub/calibration course
- `mp_restart_level` / `restart_level` - reloads the current map
- `mp_select_level <mapname>` / `select_map <mapname>` - changes level to the specified map
- `transition_map` - if the map has a `@transition_script`, goes to the next map in the sequence

"Go to hub" is exposed in the VGUI pause menu, making this one especially problematic since curious players might click it without malicious intent, but any of them can be used by typing them into the console. For normal P2 Coop where you're only going to be playing with 1 person (usually a trusted friend) this is fine, but on dedicated servers where anyone can join/leave, clients shouldn't have access to this.

A method should be added to disable the use of these, such as a cvar. This should also disable the "go to hub" option in the VGUI pause menu, since otherwise I think it would softlock on the waiting dialog.

**Comment by Luke18033** [comment]
Further note, if a cvar is used for this it should be `replicated`, so Panorama/VGUI can check it to easily enable/disable buttons

**Comment by Luke18033** [comment]
Might make sense to just always disable these in true multiplayer mode

**Comment by JJL772** [comment]
These are now disabled when running "true" multiplayer. Let me know if I missed any

**Comment by Luke18033** [comment]
IIRC there are some more in portalmp gamerules, which I didn't know about when I opened this... Not sure if any of them are harmful/problematic though.

**Comment by JJL772** [comment]
I'll have a look then

**Comment by Luke18033** [comment]
I think that's where the coop credits stuff is, those should probably be limited to the host/dedicated server console only
