### ISSUE TITLE
Multiplayer console spam from missing CS:GO cvars

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1158]
### Describe the bug

When starting a multiplayer game there's a bunch of console spam regarding missing CS:GO cvars, like this:
```
[server_p2][WARN]   ammo_grenade_limit_default - missing cvar specified in bspconvar_whitelist.txt
[server_p2][WARN]   ammo_grenade_limit_flashbang - missing cvar specified in bspconvar_whitelist.txt
[server_p2][WARN]   ammo_grenade_limit_total - missing cvar specified in bspconvar_whitelist.txt
[server_p2][WARN]   ammo_item_limit_healthshot - missing cvar specified in bspconvar_whitelist.txt
[server_p2][WARN]   bot_allow_grenades - missing cvar specified in bspconvar_whitelist.txt
[server_p2][WARN]   bot_allow_machine_guns - missing cvar specified in bspconvar_whitelist.txt
```
The file referenced (`bspconvar_whitelist.txt`) doesn't seem to actually exist anywhere, so I'd assume these are defaults being loaded from code.

### Issue Map

Any

### To Reproduce

1. Load any map in multiplayer (e.g. `sv_portal_gamemode_override mp;maxplayers 32;map mp_coop_community_hub`)
2. Look in the console

### Operating System

Tested on Windows 10

**Comment by Luke18033** [comment]
It's not loading defaults from code, this happens if you have CS:GO mounted. This should probably be blocked from loading from mounts.

**Comment by JJL772** [comment]
I don't see any references to this in code

**Comment by Luke18033** [comment]
Well, it is loading the file, putting a copy in the p2ce folder with the CS:GO cvars removed got rid of the console spam

**Comment by JJL772** [comment]
This file was apparently being loaded from the game search path, so it was probably being pulled in from CSGO for you. I've changed it to pull from `MOD`, and I think we should add an empty `bspconvar_whitelist.txt`

**Comment by Luke18033** [comment]
Does the file even do anything? I thought it had to do with the CSGO game modes system or something

**Comment by JJL772** [comment]
Anything that derives from MP gamerules does, and `execwithwhitelist`. Our coop gamerules don't subclass the MP gamerules though
