### ISSUE TITLE
CS:GO ScriptPrint... functions are missing

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1163]
### Describe the bug

The various `ScriptPrint...` [functions](https://developer.valvesoftware.com/wiki/List_of_CS:GO_Script_Functions#Printing_and_drawing) from CS:GO are missing in P2CE.

### Issue Map

Any

### To Reproduce

1. Open any map
2. Run `script ScriptPrintMessageCenterAll("test")`
3. Error

### Operating System

Tested on Windows 10

**Comment by ozxybox** [comment]
This was added in the last update.
