### ISSUE TITLE
GetPlayerName VScript function

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1169]
### Which component should be improved?

Entity

### Describe your suggestion

Add a `GetPlayerName()` function that can be called on players to return their username, for display in the world or the like

**Comment by craftablescience** [comment]
This has been implemented as a method on the return value of `GetPlayer()` for convenience, so its `GetPlayer().GetPlayerName()`

**Comment by Luke18033** [comment]
By "the return value of GetPlayer()" I'd assume you just mean any `player` entity? I was asking for this mainly for multiplayer, where `GetPlayer()` doesn't work.

**Comment by craftablescience** [comment]
Any player entity, yep

**Comment by ozxybox** [comment]
This was shipped in the last update.
