### ISSUE TITLE
Non-VAC internet servers print misleading message on startup (Valve bug)

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1170]
### Describe the bug

When a non-VAC-protected server (currently the default in P2CE) is started, this message is printed to the console:
```
Initializing Steam libraries for INSECURE Internet server.  Authentication and VAC not requested.
```
...but the "authentication not requested" part of this is misleading, because the server does still require clients to be authenticated with Steam, it just doesn't run VAC. Only LAN servers have authentication disabled.

I'd suggest changing the message to:
```
Initializing Steam libraries for INSECURE Internet server.  VAC will not run on clients.
```

### Issue Map

N/A

### To Reproduce

1. Start a non-VAC internet server (listen or dedicated)
2. Look in the console

### Operating System

All

**Comment by ozxybox** [comment]
This was shipped in the last update.
