### ISSUE TITLE
Cosmetic unlock system

### ISSUE THREAD

**Issue by Konclan** [StrataSource/Portal-2-Community-Edition#118]
A way to earn community made cosmetics through playing maps, certain reward pools could be limited to coop or singeplayer. I don't think the system should care if you cheat through a map. All it should care about is if you complete a map and then rate it (not rating it and then skipping). This could add insensitive to play community maps and rate them for both singleplayer and coop. This reward could be limited to have a daily cap. I'm not sure on what your plans are for if you're making a community market. If there is no market (which I would like), then drops could not be duplicates and could not be traded. I don't think there should be competition for certain items given the nature of Portal 2. Everything should be earn able by the player.

**Comment by FrozenDragon0** [comment]
What about the original items that are already in portal 2? Any plans to remove them/keep them? I think some people would really appreciate a way to obtain unobtainable items in portal 2 such as most of the TF2 cross overs and the promotional items.

**Comment by ozxybox** [comment]
I quite like the idea of rewarding the player for playing community maps! 
Regardless, I'm going to close this issue for now. It's not something we can reasonably action on at the current moment and has quite a large scope. We can always reopen in the future if we choose to.
