### ISSUE TITLE
Feature: Make Static Props respect Adhesion color ConVar

### ISSUE THREAD

**Issue by ErinRoseWebs69** [StrataSource/Portal-2-Community-Edition#1190]
### Which component should be improved?

Entity

### Describe your feature suggestion in more detail

If the color value of static props in the BSP file itself is a string and not in bytes, allowing static props to be able to read CVar values to define colors (namely for the gel pipes) would be useful for aesthetics.

if i make a map using adhesion gel, and one person's cvar is "0 255 0", while another person's is "255 0 175", allowing a static prop (again, namely gel pipes) to read that cvar and set its color to that cvar would make it so Person 1's gameplay shows the green pipe, while Person 2's gameplay shows the purple pipe. idk if im explaining this well.

this would only apply if the color value in static props are read as strings and not in bytes. im not gonna ask yall to rewrite the entire system for this.

**Comment by ozxybox** [comment]
Closing as superseded by #1358
