### ISSUE TITLE
Make rocket turret range configurable

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1202]
### Which component should be improved?

Entity

### Describe your suggestion

Make the range of rocket turrets configurable like it is for bullet turrets. Currently this is shown as a keyvalue in Hammer for reference, but it's read only since the actual value in code is hardcoded to 8192
![image](https://user-images.githubusercontent.com/19228201/218973981-cc656753-28ba-47b3-9864-572d4f030a7d.png)

**Comment by pivotman319-owo** [comment]
This has been implemented in newer builds

![customizable rocket turret range](https://github.com/StrataSource/Portal-2-Community-Edition/assets/15126754/73132f19-3c81-4df3-80cb-a41726fcece1)
