### ISSUE TITLE
Rocket turret skin doesn't reset when rocket lifetime expires

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1205]
### Describe the bug

If a rocket turret has a rocket lifetime set, and the lifetime expires, the rocket turret's skin won't reset to the green eye.

https://user-images.githubusercontent.com/19228201/218986773-5f8e4899-40d5-4bec-8ac1-429069617bdc.mp4

### Issue Map

escape_01 from Portal 1

### To Reproduce

1. Open escape_01 and go to the rocket turret
2. Set the rocket/speed lifetime to be low (`ent_fire laser_1 addoutput "rocketspeed 100";ent_fire laser_1 addoutput "rocketlifetime 1"`)
3. Have it fire a rocket
4. The eye doesn't reset

### Operating System

Tested on Windows 10

**Comment by pivotman319-owo** [comment]
Fixed in newer dev builds.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/15126754/538b3e84-01f7-40c4-b1df-2879f1938612
