### ISSUE TITLE
Rocket turret fire delay keyvalue

### ISSUE THREAD

**Issue by vrad-exe** [StrataSource/Portal-2-Community-Edition#1209]
### Which component should be improved?

Entity

### Describe your suggestion

Rocket turrets should have a keyvalue to set the delay between when they lock on to the player and when they fire. This keyvalue would be used for both normal mode and tripwire mode, instead of tripwire mode automatically removing the fire delay.

**Comment by ozxybox** [comment]
Fixed by @craftablescience in the next staging build
