### ISSUE TITLE
Bug: Game crashes when fizzling a weapon_portalgun that has fired portals

### ISSUE THREAD

**Issue by Equalizer5118** [StrataSource/Portal-2-Community-Edition#1211]
### Describe the bug

After creating portals with a weapon_portalgun and, by using a trigger_weapon_strip, dropping the gun on the ground and then fizzling that gun, the game will crash.

### Issue Map

N/A, easily tested here: https://www.mediafire.com/file/prk8e9t2vvrjyw4/pgun_fizzle_crashtest.bsp/file

### To Reproduce

1. Open the above map
2. Shoot a portal at any wall (does not have to be connected)
3. walk through the arch on the left to drop the gun
4. if the gun hits the fizzler, observe crash. If not, keep trying

### Operating System

Tested on Windows 11

**Comment by Luke18033** [comment]
It now makes the portals fired by the gun close, which I guess makes sense but might not have been the desired behavior here

https://user-images.githubusercontent.com/19228201/232657679-5d4c683b-9e29-4cb1-b7d1-e4e6533712ca.mp4

**Comment by JJL772** [comment]
Make a separate issue for the true desired behavior then
