### ISSUE TITLE
Bug: static props lose collision when near a portal.

### ISSUE THREAD

**Issue by Trico-Everfire** [StrataSource/Portal-2-Community-Edition#1217]
### Describe the bug

Static props (and maybe dynamic props too, it doesn't appear to do the same with dynamic props, though, I haven't tested that too much.

[bruh.webm](https://user-images.githubusercontent.com/55441008/226130537-e462112c-6ba7-452f-9930-87c0e90c9994.webm)

### Issue Map

sp_a3_03

### To Reproduce

1. Open sp_a3_03
2. walk towards the portalable surface wall that's in front of the railing.
3. Portal 1 portal, and a second one on another wall.
4. you fall through.

### Operating System

Linux

**Comment by MyGamepedia** [comment]
Very strange that this has not been found before... Are you prohibited from intentionally search for bugs ?

**Comment by Trico-Everfire** [comment]
I'll be honest, this kinda happened a few weeks ago when I was working on my FNaF map, but I thought that when it happened there, I was doing something fucky, only now, when I replayed a3 for inspiration on Old Aperture, I noticed that... it's just all static props, not just the ones I had.

**Comment by Trico-Everfire** [comment]
as for intentionally looking for bugs... I don't P2CE that much, much less than I should. I got busy with programming and such. Why others haven't found this... well, I couldn't tell.

**Comment by MyGamepedia** [comment]
I mean in general.

**Comment by AWildErin** [comment]
We have people in the beta test *to* search for bugs. That's why it exists, we want people to search for bugs in P2CE

**Comment by Trico-Everfire** [comment]
I think what they mean is, given you lads have those people, and static props being close to portals is a extremely common occurance, that it hasn't been found before, despite the fact it's been a while since last update.

**Comment by Equalizer5118** [comment]
Yeah, I have experienced this bug but I thought it was just an issue with my level. Also i can confirm that this works with static world portals as well, and that you have to be withing a (I think) 64 hammer unit radius for the clipping effect to happen.

**Comment by ozxybox** [comment]
This has been fixed internally. Should be out when the next update hits.

**Comment by Trico-Everfire** [comment]
Confirmed to be fixed on latest.

**Comment by Trico-Everfire** [comment]
Yup, it is, thanks!

**Comment by pivotman319-owo** [comment]
Confirmed fixed on latest dev.
