### ISSUE TITLE
Bug: cl_showpos no longer works under VGUI

### ISSUE THREAD

**Issue by Trico-Everfire** [StrataSource/Portal-2-Community-Edition#1224]
### Describe the bug

cl_showpos shows you your position and angle, it functions in Panorama, but does not show up in VGUI, something Default Portal 2 does. This is likely engine wide, but given Momentum Mod no longer uses VGUI it's sort of P2CE exclusive. 

### Issue Map

any. (sp_a2_triple_laser)

### To Reproduce

1. be on VGUI.
2. open any map, sp_a2_triple_laser for example.
3. cl_showpos 1
4. no show pos.

### Operating System

N/A

**Comment by AWildErin** [comment]
This was removed as it was added in panorama. It likely won't return for vgui.

**Comment by Trico-Everfire** [comment]
Whilst Panorama is still in development, wouldn't it be good to have these essential debug options available to map makers?

**Comment by JJL772** [comment]
Use net_graph
