### ISSUE TITLE
Messed up scaling with static props

### ISSUE THREAD

**Issue by JakovVinovcic** [StrataSource/Portal-2-Community-Edition#1228]
For some reason when I try to change the scale of a certain prop now, it either gets wide or the props just look really weird. Here are some example photos:
![image](https://user-images.githubusercontent.com/81032027/229243700-2ba37059-857c-4a06-831d-0d2e651a948e.png)
![image](https://user-images.githubusercontent.com/81032027/229243772-8520d3af-e23a-45d9-9388-2dacc8f06803.png)

**Comment by ozxybox** [comment]
Thank you for reporting this. We are aware of the issue and a fix is currently being deployed! Our CI is a bit slow at the moment, but the update should be out in an hour or two.

**Comment by ozxybox** [comment]
Update with the fix should be live on Steam!
