### ISSUE TITLE
Gels for PBR

### ISSUE THREAD

**Issue by JVGRYT** [StrataSource/Portal-2-Community-Edition#1233]
### Which component should be improved?

Render

### Describe your suggestion

At the moment, gels do not appear on PBR textures. I don't even know if it is possible to make gels appear on PBR, but if it is, then that would be great, as my mod is going to very much base itself on stunning graphics and the paintgun, and maybe a little bit of my own creativity. _Maybe._ Also, while you're at it, could you please add gel skins to the Schroedinger's cube and fix the missing adhesion gel skin on cubes?

:-)

**Comment by AWildErin** [comment]
Could you make the missing skin a separate issue please? It'll get fixed when a refactor to paint comes, but for now it'd be wise to  get that fixed before then.

**Comment by JVGRYT** [comment]
> Could you make the missing skin a separate issue please? It'll get fixed when a refactor to paint comes, but for now it'd be wise to  get that fixed before then.

Alright, I'll make it separate when I have time.
