### ISSUE TITLE
Bug: Info_particle_system appearing under buggy

### ISSUE THREAD

**Issue by tmob03** [StrataSource/Portal-2-Community-Edition#1238]
### Describe the bug

Under the buggy (note: not in `d2_coast_01` before the buggy gets dropped by the magnet), there is a blinking info_particle_system 
![image](https://user-images.githubusercontent.com/33987871/230705011-bd145866-0b20-4259-bfeb-d5583d640bba.png)

### Issue Map

d2_coast_03

### To Reproduce

1. Open a map with the buggy
2. Look under it
3. Notice blinking info_particle_system

### Operating System

Windows 10 Home 19045

**Comment by MyGamepedia** [comment]
Is it issue because of ep2 car ? This happen with any orange box engine based game, but not in Half Life 2.

**Comment by AWildErin** [comment]
This is because both the episodic jalopy and hl2 jeep use the same entity name and ep2 has its own copy of the jeep code that adds these lights

**Comment by Luke18033** [comment]
Should probably just have it check the model for these attachment points, and only add the lights if they're actually there.

**Comment by AWildErin** [comment]
See https://github.com/StrataSource/Portal-2-Community-Edition/issues/1288#issuecomment-1585979752

**Comment by tmob03** [comment]
Done in staging
