### ISSUE TITLE
Add Entities.DispatchSpawn VScript function

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1241]
### Which component should be improved?

Entity

### Describe your suggestion

VScript has the ability to spawn entities with `Entities.CreateByClassname()`, but there's a major limitation with it: the entity's internal `Spawn()` function in code will never be called, resulting in most entities spawned this way not working correctly. In TF2 VScript, they added a `Entities.DispatchSpawn()` function you can call which takes in an entity handle as the parameter; this should be ported/added to P2CE as it would largely expand what can be done with VScript with a relatively small addition.

**Comment by JJL772** [comment]
In the meantime you can use `CreateEntityByName(className, keyValues)`, which properly invokes spawn. Might rename it to `CreateEntityByClassname` though or something.

**Comment by Luke18033** [comment]
Oh, did P2CE add that?

**Comment by JJL772** [comment]
Yep

**Comment by Luke18033** [comment]
These things really need to be documented better, I had no idea that existed. Not sure if this is still useful then, but maybe it should still be added just for parity with TF2 (or in case it's somehow useful to create an entity but not dispatch spawn until later?)

**Comment by JJL772** [comment]
Yeah definitely going to add the `DispatchSpawn` thing. I also forgot to update the wiki docs with that, would be nice if that could be automated eventually. We generally do a pretty good job detailing what was added/changed in the changelog channel at least

**Comment by JJL772** [comment]
Done
