### ISSUE TITLE
"player_hurt" game event doesn't fire

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1245]
### Describe the bug

The `player_hurt` game event does not appear to fire when a player takes damage. It should include parameters for the player ID of the attacker, the player ID who took damage, and their remaining health.

### Issue Map

Any

### To Reproduce

1. Set `net_showevents 2`
2. Damage a player
3. No event is fired

### Operating System

Tested on Windows 10

**Comment by JJL772** [comment]
Are we sure this is broken? I hooked this as a part of a limited test for the panorama game events API and it seemed to work fine there: https://github.com/StrataSource/p2ce-panorama-ui/commit/0648d02dccf29b8885dd6403700fd97604cca469

**Comment by Luke18033** [comment]
Hmm, I haven't actually tried hooking it up to an event listener yet, just noticed it wasn't showing up in the `net_showevents` output - perhaps that command is actually what's broken?

**Comment by JJL772** [comment]
Would be funny!

**Comment by Luke18033** [comment]
Hmm, I think `net_showevents` only outputs info about events that are actually being listened to, once I added an event listener for it it started showing up, and removing the event listener made it stop showing up again. That's possibly intended behavior, although it is a little confusing.

**Comment by JJL772** [comment]
Try `display_game_events`?

**Comment by Luke18033** [comment]
Seems to behave the same way

**Comment by JJL772** [comment]
Open an issue about that behavior, shouldn't be too hard to fix
