### ISSUE TITLE
Bug: weapon_hopwire causes game crash if you try to pickup something

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1263]
### Describe the bug

weapon_hopwire causes game crush if you'l try to pickup something by E key. Happen only with already dropped hopwire by player, not by created grenade thanks `ent_create npc_grenade_hopwire` or if just have the weapon. More in video (at the end I'll try to pickup cube).
![20230418195028_1](https://user-images.githubusercontent.com/103366204/232850520-9e5cb40d-1602-4dba-8bec-cf47cea5e267.jpg)

https://user-images.githubusercontent.com/103366204/232857176-26ef6f57-dbbd-4ae5-bc86-a4d060278b17.mp4

### Issue Map

Any.

### To Reproduce

1. Open any map.
2. Enter in console `give weapon_hopwire`.
3. Enter in console `use weapon_hopwire`.
4. Drop hopwire.
5. Try to pickup any object.

**Comment by MyGamepedia** [comment]
I'll edit it, this happening with anything.

**Comment by MyGamepedia** [comment]
Now already! ^_^

**Comment by MyGamepedia** [comment]
Maybe [Compat: Portal 1](https://github.com/StrataSource/Portal-2-Community-Edition/labels/Compat%3A%20Portal%201) ? It wasn't ever available in Half Life 2 games (if not included ep 1 old version), only in Portal.

**Comment by Luke18033** [comment]
Why do we even have this entity, isn't it an hl2 beta thing?

**Comment by MyGamepedia** [comment]
> Why do we even have this entity, isn't it an hl2 beta thing?

We have it in original Portal.

**Comment by Luke18033** [comment]
Okay, I'm asking why P2CE has it, considering that it's a cut weapon and not really supported

**Comment by MyGamepedia** [comment]
> Okay, I'm asking why P2CE has it, considering that it's a cut weapon and not really supported

Well... Compatibility with Portal ? Some mods can use it. Just why not, lol.

**Comment by MyGamepedia** [comment]
It have really interest mechanic, it's compatible with portals and looks pretty fun. I plan to use it in my own mod.

**Comment by tmob03** [comment]
Closed by the removal of this entity in staging.
