### ISSUE TITLE
Portal 2 Bug: npc_security_camera collides with npc clip brush even if it's a prop

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1271]
### Describe the bug

`npc_security_camera` collides with npc clip brush even if it's a physics prop, it's just shouldn't to be like this. Also - it's strange behave with portals (more in the [video](https://user-images.githubusercontent.com/103366204/233377076-e4b251ad-04d2-4db1-9e4e-e2d0d645b175.mp4)).
![20230420160448_1](https://user-images.githubusercontent.com/103366204/233376736-1a273962-201a-4671-82d0-9dc349849217.jpg)

I've found it earlyer in my own mod. Should work in Portal 2 sure.
![Portal_Screenshot_2022 08 30_-_17 51 37 97](https://user-images.githubusercontent.com/103366204/233376782-5d9a4c9a-6078-4d71-bbc2-b7f989daa070.png)

### To Reproduce

1. Open any map with npc clip and `npc_security_camera`, or just test it here [cam_test.zip](https://github.com/StrataSource/Portal-2-Community-Edition/files/11286536/cam_test.zip).
2. Place portal under camera.
3. Grab dropped camera.
4. Try to move it through npc clip brush.

### Operating System

Any

**Comment by AWildErin** [comment]
Does the same thing happen to turrets? if it does the logic should be easier to merge over, but at the end of the day it's still an NPC, whether in prop form or not, so I wouldn't say this is really a "bug"

**Comment by MyGamepedia** [comment]
> Does the same thing happen to turrets? if it does the logic should be easier to merge over, but at the end of the day it's still an NPC, whether in prop form or not, so I wouldn't say this is really a "bug"

It's have sense for turret's, BUT NO for cameras. Camera can't kill someone, it's even never move and at default state never work with npc clip. At least - it's not convenient.

**Comment by AWildErin** [comment]
Spoke internally, and this logic won't change. Yes the NPC not colliding with the clip going through the brush *is* an issue, but it's honestly not a problem in any capacity.

**Comment by MyGamepedia** [comment]
Well.. I'll just replace it to feature.
