### ISSUE TITLE
Bug: Weapons don't push npc_security_camera even if it's a physics prop

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1278]
### Describe the bug

Weapons don't push `npc_security_camera` even if it's a physics prop. The same in Portal and maybe in Portal 2.

https://user-images.githubusercontent.com/103366204/233663429-6aa410b1-bdb9-4eca-b0c1-30ccb318acb3.mp4

### Issue Map

Any.

### To Reproduce

1. Open this map for quick test [camera_test.zip](https://github.com/StrataSource/Portal-2-Community-Edition/files/11296121/camera_test.zip).
2. Shoot in camera which sparking at start (the second is `prop_physics_override`).

### Operating System

Any.

**Comment by AWildErin** [comment]
This is not really a bug. Not sure in what circumstances this would even be useful to fix.

**Comment by MyGamepedia** [comment]
There Valve uses hacks sure... as minimum because camera save class name.

**Comment by MyGamepedia** [comment]
I would leave it, you could just place very low priority.

**Comment by MyGamepedia** [comment]
This is a bug at least, it's should be fixed ever. No matter how critical or not.

**Comment by AWildErin** [comment]
> There Valve uses hacks sure... as minimum because camera save class name.

I'm not sure what you're asking for here, the class doesn't change in any capacity. All the code does is just enable physics, it's still an NPC lol.

**Comment by MyGamepedia** [comment]
> > There Valve uses hacks sure... as minimum because camera save class name.
> 
> I'm not sure what you're asking for here, the class doesn't change in any capacity. All the code does is just enable physics, it's still an NPC lol.

Yes, but it's should be `simple_prop_physics` after `ragdoll` command, because this "hack" call some problems like pushing or npc clips. So, it's just should convert, `phys_convert` already can do so.

https://user-images.githubusercontent.com/103366204/233844485-11c1deee-b124-4a3a-bbcc-ad92e539be69.mp4
