### ISSUE TITLE
Bug: The ammo box on the back of the buggy doesn't work

### ISSUE THREAD

**Issue by tmob03** [StrataSource/Portal-2-Community-Edition#1288]
### Describe the bug

On the back of the scout car there is an ammo box, that when +use'd gives SMG1 ammo. It doesn't work in P2CE

### Issue Map

d2_coast_03

### To Reproduce

1. Open d2_coast_03
2. Try and get ammo from the ammo box

### Operating System

Windows 10 Home 19045

**Comment by MyGamepedia** [comment]
The same in Portal.

**Comment by Luke18033** [comment]
This is probably just because it's using the ep2 car class instead of the hl2 one

**Comment by MyGamepedia** [comment]
Maybe do for it checking, I mean that if model have `ammo_close`/`ammo_open` animations - game will enable the ammo box.

**Comment by MyGamepedia** [comment]
Not worst solution for compatibility I think (if it's possible).

**Comment by AWildErin** [comment]
So an update on this. We have seemingly split them into two entities, `prop_vehicle_jeep_hl2` and `prop_jeep_vehicle_episodic` for mappers. For compatibility, we added a way to alter which entity will be used when spawning `prop_vehicle_jeep` on maps, however, this is entirely dependent on the cvar `hl2_episodic`, which defaults to 1.

**Comment by tmob03** [comment]
> So an update on this. We have seemingly split them into two entities, `prop_vehicle_jeep_hl2` and `prop_jeep_vehicle_episodic` for mappers. For compatibility, we added a way to alter which entity will be used when spawning `prop_vehicle_jeep` on maps, however, this is entirely dependent on the cvar `hl2_episodic`, which defaults to 1.

Nice! Fixed with the above
A hack for sure, but could this cvar be made to default to 0 when the map name starts with `d2_coast_` to at least account for the biggest example of the cvar mismatching what is intended to occur.

**Comment by AWildErin** [comment]
I'm not sure a good fix for this. I've asked internally so I'll see what we can do, setting it based on the cvar is less than ideal incase people have other maps that have `prop_vehicle_jeep`

**Comment by MyGamepedia** [comment]
> So an update on this. We have seemingly split them into two entities, `prop_vehicle_jeep_hl2` and `prop_jeep_vehicle_episodic` for mappers. For compatibility, we added a way to alter which entity will be used when spawning `prop_vehicle_jeep` on maps, however, this is entirely dependent on the cvar `hl2_episodic`, which defaults to 1.

Is it from Mapbase ?

**Comment by AWildErin** [comment]
No.
