### ISSUE TITLE
voice_vox missing

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1293]
### Describe the bug

The `voice_vox` cvar appears to be missing (or devonly), preventing open mic mode from being used/saved.

### Issue Map

N/A

### To Reproduce

1. Open console
2. Type `voice_vox`
3. It's not there

### Operating System

Tested on Windows 10

**Comment by craftablescience** [comment]
It's not devonly, and we're not making existing cvars devonly unless its for a good reason

**Comment by Luke18033** [comment]
It might have been compiled out entirely, since CS:GO got rid of it - maybe commented out or behind a specific `#ifdef`

**Comment by JJL772** [comment]
Not marked as devonly anymore
