### ISSUE TITLE
Bug: Broken game_text channels in Panorama

### ISSUE THREAD

**Issue by Doclic** [StrataSource/Portal-2-Community-Edition#1298]
### Describe the bug

The `game_text` entity has channels that control text size.
Channels 2 and 3 should make the text small and big respectively, but instead they both make the text invisible.

### Issue Map

VMFs (gzipped so that GitHub allows me to upload):
[channel1.vmf.gz](https://github.com/StrataSource/Portal-2-Community-Edition/files/11320455/channel1.vmf.gz)
[channel2.vmf.gz](https://github.com/StrataSource/Portal-2-Community-Edition/files/11320548/channel2.vmf.gz)
[channel3.vmf.gz](https://github.com/StrataSource/Portal-2-Community-Edition/files/11320550/channel3.vmf.gz)

### To Reproduce

1. Open linked maps
2. Go to the trigger in front of your spawn point
3. See that only channel 1 works

**Comment by Luke18033** [comment]
The font used for the other channels is also wrong, it should be Univers and bigger

**Comment by ozxybox** [comment]
This is fixed in staging. Thanks Stefan!
