### ISSUE TITLE
Allow changing model of portal 2 element props

### ISSUE THREAD

**Issue by Khronophobia** [StrataSource/Portal-2-Community-Edition#130]
This is already possible with VScript but it's a little buggy. One reason of doing this instead of using a prop_dynamic is that the animations won't snap to the first frame

- [x] prop_button
- [x] prop_floor_cube_button
- [x] prop_floor_ball_button
- [x] prop_under_button
- [x] prop_under_floor_button (maybe?)
- [x] prop_testchamber_door
- [x] prop_tractor_beam (hardcoded toggle between 192 and 128 models)
- [x] prop_wall_projector
- [x] prop_laser_relay
- [x] prop_linked_portal_door
- [ ] prop_monster_box (swap between two models dynamically)
- [x] prop_glados_core (useless in P2?)
- [x] npc_security_camera
- [x] npc_personality_core (hardcoded toggle between Wheatley and Corruputed models)
- [x] npc_rocket_turret
- [x] prop_exploding_futbol (Bombs used in the final game)
- [x] prop_glass_futbol

**Comment by Luke18033** [comment]
Specifically, switching the model using VScript causes the close/open animations to be swapped (so `Close`ing the door opens it, but plays close sounds and closes the areaportal). You need to swap those animations in the model so that it plays the right ones. It'd be a lot nicer to just be able to set it by keyvalue.

**Comment by SpyceTewan** [comment]
There's other entities that can only have its model changed through vscript. npc_security_camera has the same issue if I recall correctly. 

Can someone provide a full list of affected entities? Marking this as a bug

**Comment by Luke18033** [comment]
@TeamSpen210

**Comment by SpyceTewan** [comment]
Can someone give the list?

**Comment by Luke18033** [comment]
These were the ones I could find:
- `prop_button`
- `prop_floor_cube_button`
- `prop_floor_ball_button`
- `prop_under_button`
- `prop_under_floor_button` (maybe?)
- `prop_testchamber_door`
- `prop_tractor_beam` (hardcoded toggle between 192 and 128 models)
- `prop_wall_projector`
- `prop_laser_relay`
- `prop_linked_portal_door`
- `prop_monster_box` (swap between two models dynamically)
- `prop_glados_core` (useless in P2?)
- `npc_security_camera`
- `npc_personality_core` (hardcoded toggle between Wheatley and Corruputed models)
- `npc_rocket_turret` (I suggested model swapping by keyvalue in #26)

**Comment by Luke18033** [comment]
Why weren't the futbol entities added to the list in the original comment?

**Comment by AWildErin** [comment]
This should be in the next steam release, however a few entities didn't get added.

- prop_testchamber_door
- prop_tractor_beam
- prop_wall_projector
- prop_monster_box
- npc_personality_core
- prop_glass_futbol

These can probably be revisited at some point

**Comment by Luke18033** [comment]
Why not those specific entities?

**Comment by AWildErin** [comment]
- chamber door, because I asked about the constant anim playing and nobody responded to me
- tractor beam and projector confused me, because I had to also look for the way they set the particle points or w/e for the size
- personality core, I look a look at and, personally, I just couldn't really be bothered to do it at the time
- and monster box and futbol I sorta forgot lol

**Comment by Luke18033** [comment]
For tbeams I'd suggest having the "use 128 model" keyvalue be set to 2 to use a custom model (same for core alt skins). Monster box should have 2 model keyvalues for extended/rectracted versions. Not sure why light bridges would be problematic, do they use attachment points to set the size of the bridge or something?

**Comment by AWildErin** [comment]
So, afaik, all of these are done. I have elected to not do prop_monster_box, the entity is very purpose-built and it's just a hassle to allow it to have a custom model.

**Comment by StefanH-AT** [comment]
@AWildErin Can this be closed? This keeps popping up in my github notifications as an unfinished item I'm assigned to for some reason

**Comment by AWildErin** [comment]
Oops yeah it can be at this rate, I'll do that.
