### ISSUE TITLE
Can't connect to non localhost servers

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1301]
### Describe the bug

Connecting to servers that aren't running on `localhost`/`127.0.0.1` appears to always fail since the latest update.

- Starting a singleplayer game or listen server works correctly
- Connecting to a dedicated server running on your machine using `connect 127.0.0.1` works correctly
- Connecting to a dedicated server running on your machine using `connect 192.168.x.x` does *not* work
- Connecting to a server over LAN does *not* work
- Connecting to a server over the internet does *not* work

Note that this does not appear to affect matchmaking (i.e. co-op games started through VGUI), those likely use a different Steam based connection method

### Issue Map

N/A

### To Reproduce

1. Run a dedicated server
2. Do `connect 192.168.x.x` (replace that with your local IP), it fails to connect
3. Have someone try to connect over the internet, it also fails

### Operating System

Tested on Windows 10

**Comment by ozxybox** [comment]
Figured it out. `-ip`'s default was accidentally changed (by me) to `loopback`, blocking all traffic into or out of the machine. Oops!

**Comment by ozxybox** [comment]
This has been done for a bit now, was waiting for the changelog to close it
