### ISSUE TITLE
Remove code to auto equip promo weapon entities

### ISSUE THREAD

**Issue by vrad-exe** [StrataSource/Portal-2-Community-Edition#1307]
### Which component should be improved?

Entity

### Describe your suggestion

Portal 2 had a set of promotional Co-op items given to those who pre-ordered the game: the Paint Job skins, the Roll Cage, and the Antenna Topper (an Aperture logo flag). However, the way these items are implemented is completely different from all the Robot Enrichment items: rather than being actual items stored in the user's inventory, they are automatically equipped if the player owns a specific DLC which was given when pre-ordering the game, as long as they don't have anything else equipped in that slot. Internally, the Paint Job skins are a secondary skin on the bots' models (whereas all the other skins use a separate copy of the model), while the Roll Cage and Antenna Topper are *weapons*, automatically given to the bots on spawn, with these classnames:

- `weapon_promo_antenna_ball` (Atlas Antenna Topper)
- `weapon_promo_antenna_egg` (P-Body Antenna Topper)
- `weapon_promo_helmet_ball` (Atlas Roll Cage)
- `weapon_promo_helmet_egg` (P-Body Roll Cage)

These "weapons" are completely useless in P2CE: we don't have the preorder DLC so they will never be given on spawn (I don't think?), and they aren't even useful as hacky custom weapons because the game prevents you from ever having them as your active weapon. If we do ever want to bring these items back, they should just be implemented normally using the econ system instead of through this hacky method.

Should probably also go and clean up the code which sets players to use the paint job skins.

**Comment by MyGamepedia** [comment]
Do not do this! Maps like F-Stop: Project Capture or the map with RPG for Portal 2 use this entities + VScripts for easy weapon recreations.

**Comment by Luke18033** [comment]
As far as I can tell you can't actually equip them, so how does that work?

**Comment by Luke18033** [comment]
Also we're not supporting f-stop recreations

**Comment by pivotman319-owo** [comment]
> Do not do this! Maps like F-Stop: Project Capture or the map with RPG for Portal 2 use this entities + VScripts for easy weapon recreations.

you can't even use these at all, they're like TF2 hats but worse

**Comment by pivotman319-owo** [comment]
mods make use of Base(HL)CombatWeapon for this, not some obscure gamestop promo entity

**Comment by Luke18033** [comment]
Also `weapon_portal_base`, which is a weapon that doesn't do anything but can otherwise still be equipped and drawn as normal.

**Comment by MyGamepedia** [comment]
I know, but it'll cut compatibility anyway.

**Comment by MyGamepedia** [comment]
> > Do not do this! Maps like F-Stop: Project Capture or the map with RPG for Portal 2 use this entities + VScripts for easy weapon recreations.
> 
> you can't even use these items at all, they're like TF2 hats but worse

You can get them in console.

**Comment by pivotman319-owo** [comment]
> I know, but it'll cut compatibility anyway.

There's no compatibility with something that's not even usable in the base game

**Comment by Luke18033** [comment]
Can you actually point to a map that's using these rather than `weapon_portal_base` etc. for custom weapons?

**Comment by MyGamepedia** [comment]
> Может ли быть указана карта, которая использует это, а не что-то `weapon_portal_base`подобное для нестандартного оружия?

https://youtu.be/ImUOwbaRnuI
https://steamcommunity.com/workshop/filedetails/?id=2777615422
https://steamcommunity.com/sharedfiles/filedetails/?id=2934902806

**Comment by MyGamepedia** [comment]
> Can you actually point to a map that's using these rather than `weapon_portal_base` etc. for custom weapons?

https://steamcommunity.com/sharedfiles/filedetails/?id=2845817091
https://steamcommunity.com/workshop/filedetails/?id=2777615422
https://steamcommunity.com/sharedfiles/filedetails/?id=2934902806
https://steamcommunity.com/sharedfiles/filedetails/?id=2666161418

**Comment by MyGamepedia** [comment]
> > > Can you actually point to a map that's using these rather than `weapon_portal_base` etc. for custom weapons?
> > 
> > 
> > https://steamcommunity.com/sharedfiles/filedetails/?id=2845817091
> > https://steamcommunity.com/workshop/filedetails/?id=2777615422
> > https://steamcommunity.com/sharedfiles/filedetails/?id=2934902806
> > https://steamcommunity.com/sharedfiles/filedetails/?id=2666161418
> 
> The first and second maps on the list use weapon_cubemap and BaseHLCombatWeapon, not the gamestop weapons

Are you sure ? You've check ?

**Comment by pivotman319-owo** [comment]
> > > > Can you actually point to a map that's using these rather than `weapon_portal_base` etc. for custom weapons?
> > > 
> > > 
> > > https://steamcommunity.com/sharedfiles/filedetails/?id=2845817091
> > > https://steamcommunity.com/workshop/filedetails/?id=2777615422
> > > https://steamcommunity.com/sharedfiles/filedetails/?id=2934902806
> > > https://steamcommunity.com/sharedfiles/filedetails/?id=2666161418
> > 
> > 
> > The first and second maps on the list use weapon_cubemap and BaseHLCombatWeapon, not the gamestop weapons
> 
> Are you sure ? You've check ?

certainly
![image](https://user-images.githubusercontent.com/15126754/235864541-0974f143-0ff2-453f-a769-737cd1dc27d8.png)

**Comment by pivotman319-owo** [comment]
ditto for punt and p2 weapon deathmatch (maps 3 and 4), both of these use weapon_cubemap and BasePortalCombatWeapon

![image](https://user-images.githubusercontent.com/15126754/235865177-fd6f1b9c-1d98-4aad-be03-98f455aebca9.png)
![image](https://user-images.githubusercontent.com/15126754/235865423-bd5381a1-b826-42fe-b605-f5b7ebb9ec70.png)

**Comment by tmob03** [comment]
> As far as I can tell you can't actually equip them, so how does that work?

I was messing with these a few days ago to add to the fgd, lol. I noticed they would be equipped either when you gave them to yourself, or you spawned one with ent_create and walked over them. Need to use third person to see them of course

**Comment by Luke18033** [comment]
By "equip" I meant pull it out and have it as your currently active weapon. That actually does seem to work though, it was behaving weirdly when I tried it last night.

**Comment by Trico-Everfire** [comment]
Why not, remove them currently, and when the scripting system comes around, replicate their behaviour in script, so that the maps become playable again. It'd be a hack ontop of a hack, but it'd make the maps playable. There's no good reason for base Portal 2, portal 1 or HL2 to keep them.

**Comment by Pacca64** [comment]
I have used these in a vanilla portal 2 workshop map to make custom viewmodels for custom weapons, alongside baseportalcombatweapon, basehlcombatweapon, weapon_portal_base, etc. Functionally they're all pretty much identical to weapon_cubemap, but with the added benefit of loading different weapon scripts, being able to be swapped between with 'use <weapon_classname>' and being able to coexist in the same map/mod. I don't really see why removing them would be an improvement, it just removes a useful base portal 2 feature (and portal 1/HL2 feature in the cases of the base portal weapons and basehlcombatweapon).

**Comment by vrad-exe** [comment]
Yeah coming back to this issue now, I think removing these would do more harm than good, especially considering the angelscript stuff is still pretty much nonexistent. I had originally suggested this because in my testing I couldn't get them to equip as the active weapon with `use`, so assumed it just didn't work - other people are saying that it does though, so I'd assume something can be changed in the weapon script to make that work as expected.

I would probably just remove the code in portalplayer that auto equips these, but leave the entities themselves for custom maps to use if needed.

**Comment by vrad-exe** [comment]
Honestly I'm even just going to close this, it's such a specific internal thing that doesn't have any actual effect (the DLC flags that make this code work will never be set in P2CE anyway), I don't really see a reason for someone to waste time going out of their way to remove it.
