### ISSUE TITLE
Game Gradually Lags

### ISSUE THREAD

**Issue by JVGRYT** [StrataSource/Portal-2-Community-Edition#1308]
### Describe the bug

Whenever I play, the FPS drops, very slowly. When I pause and exit the program, it speeds up the process. I've gotten down to under 20fps at this point. I'm not sure it's a common issue, but it should probably be fixed anyway. Let me know if it works normally for other people

### Issue Map

N/A

### To Reproduce

1. Open the game
2. Play on a map for a while
3. Pause and exit for a while
4. Frame drops drasticslly

### Operating System

Windows 11

**Comment by JJL772** [comment]
This is a known issue that has already been fixed internally. I'll close this once we push a new build to steam.

Appreciate the report though!

**Comment by JJL772** [comment]
Fixed in latest release
