### ISSUE TITLE
Bug: missing shader update makes certain CSGO models not render in Hammer's 3D viewport. 

### ISSUE THREAD

**Issue by ErinRoseWebs69** [StrataSource/Portal-2-Community-Edition#1320]
### Describe the bug

certain AO files give shader errors in Hammer, and the mesh doesnt render in the 3D viewport, but can still be selected in the 3D viewport. attached is the VMT and associated VTFs for a material. file path to go in: `materials/models/props/de_aztec/hr_aztec/aztec_walls`
[hr_aztec_wall_stone_01_grey_color.zip](https://github.com/StrataSource/Portal-2-Community-Edition/files/11459252/hr_aztec_wall_stone_01_grey_color.zip)

### Issue Map

no map associated, as its in Hammer.

### To Reproduce

1. open Hammer
2. make a prop_static
3. set model to `models/props/de_aztec/hr_aztec/aztec_walls/aztec_wall_stone01_bridge_foundation_01.mdl` (notice; it cant be seen in 3D viewport)
4. check Messages window for the error.

**Comment by ozxybox** [comment]
Closed, as this was fixed IIRC
