### ISSUE TITLE
Bug: No sparks when player shoot and realod crossbow

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1330]
### Describe the bug

In original `Half Life 2` crossbow create sparks when player shoot and reload weapon, this not happen in P2CE (it's not missed particles).

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/8997a92f-1308-41e1-9ac3-7b2782336f99

### Issue Map

Any.

### To Reproduce

1. Open any map.
2. Enter in console give `weapon_crossbow; use weapon_crossbow`.
3. Shoot.
4. Pay attention that it's not create sparks.

### Operating System

Any.

**Comment by AWildErin** [comment]
related to #850

**Comment by MyGamepedia** [comment]
> related to #850

I mean on gun, not when the bolt touches surface. By the way, when bolt touches surface - it create sparks (sorry if incorrect understand you).

**Comment by AWildErin** [comment]
I know, I'm just making a note that the cause of this is the same as the issue I mentioned

**Comment by pivotman319-owo** [comment]
the bugfix for this caused a seperate regression in the reload code that occurs unless you give the player some crossbow ammo

https://github.com/StrataSource/Portal-2-Community-Edition/assets/15126754/15580655-65de-4ede-adc7-28dfdbcf7b43

**Comment by pivotman319-owo** [comment]
issue fixed in staging and dev

**Comment by MyGamepedia** [comment]
> issue fixed in staging and dev

So fast...
