### ISSUE TITLE
Remove npc_houndeye

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1334]
### Which component should be improved?

Entity

### Describe your suggestion

No idea why, but it's in game! Just launch any `Black Mesa` map to check it, or enter in console `ent_create npc_houndeye`. It's work if add model from `Half Life: Source` but it's still useless for P2CE. In HL:S something wrong with his AI, in almost it don't wont to walk to player if player far from it, sure that it's so also in P2CE. If someone will need houndeye - he probably can recraete it with CScripts. So, houndeye should be removed from P2CE.

![Portal 2 Community Edition Screenshot 2023 05 28 - 21 07 08 59](https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/f2a1e6e8-ab2d-4742-bedb-979f76588cc5)

![Portal 2 Community Edition Screenshot 2023 05 28 - 21 06 03 68](https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/bdb0fad5-2f02-4746-8104-a2d1fd4732e2)

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/e7d413fc-c562-45cb-b6e3-f31abd32edca

**Comment by tmob03** [comment]
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/33987871/06240d66-d305-4b8c-927c-5c349b5bb586)
Done in staging

**Comment by MyGamepedia** [comment]
> ![image](https://user-images.githubusercontent.com/33987871/242513756-06240d66-d305-4b8c-927c-5c349b5bb586.png) Done in staging

You have dev build ?

**Comment by AWildErin** [comment]
They are a QA tester, they have access to a staging build which is given to a select few testers before it hits the rest of the playtesters. Reason is because sometimes we have *major* regressions and it's nice to catch them before they hit nightly
