### ISSUE TITLE
Bug: Game unable to give portal gun through sp_transition_list.nut

### ISSUE THREAD

**Issue by OrinjiNeko** [StrataSource/Portal-2-Community-Edition#1338]
### Describe the bug

When a sequence of maps are added in the transition list, you do not spawn with the portal gun when indicated to, and presented with this in the console:

```
[vscript] =======================Trying to run give_portalgun
[vscript] =======================Trying to run upgrade_portalgun
[engine] This game doesn't allow cheat command give_portalgun in single player, unless you have sv_cheats set to 1.
[engine] This game doesn't allow cheat command give_portalgun in single player, unless you have sv_cheats set to 1.
[engine] This game doesn't allow cheat command upgrade_portalgun in single player, unless you have sv_cheats set to 1.
[engine] This game doesn't allow cheat command upgrade_portalgun in single player, unless you have sv_cheats set to 1.
```

### Issue Map

N/A

### To Reproduce

1. Add maps to sp_transition_list.nut
2. Open map
3. No portal gun

### Operating System

Windows 10

**Comment by MyGamepedia** [comment]
I today find similar thing, but for `point_clientcommand`. It's not convenient.

![20230531162625_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/616e5a89-38e3-4ca9-bccc-fb213700479f)

**Comment by Luke18033** [comment]
This would happen if you are using a modified version of the script which is based on the one from `portal2/` instead of the one from `update/`. In DLC1 (when they added challenge mode) they changed the transition script to give the portal gun through dedicated VScript functions so that they could cheat protect these commands.
