### ISSUE TITLE
Bug: comp_vactubes sometimes won't let you compile

### ISSUE THREAD

**Issue by Komikmmm** [StrataSource/Portal-2-Community-Edition#1340]
### Describe the bug

Whenever I fast compile a map theres a 80% chance this error will appear, when it _does_ work, the vactubes are fine.
```
ValueError: No source found for junction junction_end at (-2592 1216 -356)!
[28408] Failed to execute script 'postcompiler' due to unhandled exception!
----------------------------------
Command failed! Process returned 1, exiting
----------------------------------
press any key to continue...```

### Issue Map

https://drive.google.com/file/d/1t0MnofT8hsuf5st8k04u7RZAnWgUmeSm/view?usp=sharing

### To Reproduce

Just compile it and It'll either compile fine or it will break

### Operating System

_No response_

**Comment by Equalizer5118** [comment]
If you are certain that your tube system is set up correctly, give each individual point a name and manually specify the next points.

**Comment by Komikmmm** [comment]
i seemed to fix it by changing the tube so yeah that worked

**Comment by ozxybox** [comment]
Closing due to  inactivity and it seems like you were able to figure it out? Not sure if further work is required or not.
