### ISSUE TITLE
Pause effect should be moved to panorama

### ISSUE THREAD

**Issue by ddddpplo** [StrataSource/Portal-2-Community-Edition#1344]
### Which component should be improved?

UI/UX

### Describe your suggestion

When the game is paused, there is a screen effect that desaturates everything and adds a slight blur. This effect is currently done in code but should be moved to panorama so it's easily changeable.
![Screenshot (13)](https://github.com/StrataSource/Portal-2-Community-Edition/assets/135053912/a9492567-0a18-4001-99d8-ecc3dff567c0)

**Comment by craftablescience** [comment]
Already not in code
