### ISSUE TITLE
Bug: HL2 flashlight doesn't go through portals

### ISSUE THREAD

**Issue by Doclic** [StrataSource/Portal-2-Community-Edition#1347]
### Describe the bug

Title.

Example images: 
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/30270428/5774d093-8978-47d8-9f29-b1f7aa245fb3)
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/30270428/10613349-b1e4-4bcf-adef-ae7886eb55a2)

### Issue Map

Any
Example: (GZipped because GitHub doesn't allow uploads of `.bsp` or `.vmf` files but does allow `.gz`)
[flashlight_bug.vmf.gz](https://github.com/StrataSource/Portal-2-Community-Edition/files/11655268/flashlight_bug.vmf.gz)
[flashlight_bug.bsp.gz](https://github.com/StrataSource/Portal-2-Community-Edition/files/11655269/flashlight_bug.bsp.gz)

### To Reproduce

1. Open map (any will work, but I made a map specifically to test this if you want)
2. Place portals
3. Type `impulse 100` in console
4. Try putting the light through a portal
5. Notice it doesn't work
6. Die out of frustration

**Comment by MyGamepedia** [comment]
Not really bug, and it's relevant to this https://github.com/StrataSource/Portal-2-Community-Edition/issues/462.

**Comment by ozxybox** [comment]
Thanks for the reminder on this issue doclic and thanks for the heads up on the duplicate gamepedia!

Closing as duplicate of #462

**Comment by ozxybox** [comment]
Oh also, awesome that you included test maps! I'll repost those to #462
