### ISSUE TITLE
Bug: Panorama debugger closes instantly

### ISSUE THREAD

**Issue by ddddpplo** [StrataSource/Portal-2-Community-Edition#1362]
### Describe the bug

When I type `panorama_debugger_toggle` in the console, it opens for a split second and then closes, and it says `**** Unable to localize '#Debugger_Inspect' on panel descendant of 'InspectButton'` in the console.

### Issue Map

N/A

### To Reproduce

1. Open P2CE
2. Type `panorama_debugger_toggle` in the console

### Operating System

Windows 10

**Comment by tmob03** [comment]
Fixed
