### ISSUE TITLE
rocket turret model

### ISSUE THREAD

**Issue by Hikkikira** [StrataSource/Portal-2-Community-Edition#1366]
### Which component should be improved?

Entity

### Describe your suggestion

Use vallachan's rocket turret model by default, it shouldn't override preexisting rocket turrets from p1 levels though.

![yes](https://github.com/StrataSource/Portal-2-Community-Edition/assets/111175647/f3c4b70b-b6fd-43e7-b4f5-cb3cb50e92f7)

**Comment by MyGamepedia** [comment]
Is this model in p2/p2ce by default?

**Comment by MyGamepedia** [comment]
Otherwise this suggestion have no sense.

**Comment by Hikkikira** [comment]
it can be added into the games assets, we know for the campain the autumn styled overgrown foliage will be added, so thers not a reason a new rocket turret model can't be

**Comment by MyGamepedia** [comment]
Well, P2CE not for adding new assets at all. We also don't know what they want to use in their campaign.

**Comment by MyGamepedia** [comment]
But this still solve developers.

**Comment by Hikkikira** [comment]
look at the store page for p2ce, the screen shots show an autumn styled overgrown chamber

**Comment by Hikkikira** [comment]
they also added a bouch of room-mover stuff, the Schrodinger cubes are also technically new assets

**Comment by AWildErin** [comment]
I’m just gonna close this. Once the workshop comes along they can upload their model there, but we won’t be shipping it by default.
