### ISSUE TITLE
Bug: ent_create hl2_gamerules cause game crash

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1377]
### Describe the bug

If create `hl2_gamerules` thanks `ent_create hl2_gamerules` - game get crash.

### Issue Map

Any.

### To Reproduce

1. Open any map.
2. Enter in console `sv_cheats 1; ent_create hl2_gamerules`.
3. Unpause game.
4. You now not in game!

### Operating System

Any.

**Comment by TeamSpen210** [comment]
The gamerules entities shouldn't have more than one existing at a time, they're not really supposed to be spawned. Not sure what mapbase did there.

**Comment by AWildErin** [comment]
Yeah, I'm not sure if this will ultimately get fixed. Spawning random entities that are not designed to be spawned and then having them crash isn't inherently something we need to fix really since... yknow, they're not designed to be spawned

**Comment by JJL772** [comment]
Console commands are supposed to be developer/modder only, the end user should rarely need to run them. If running one causes the game to crash, it borders on "wontfix" territory. Spawning random entities is 100% in won't fix territory because there is no tangible benefit in us fixing them.

**Comment by MyGamepedia** [comment]
> The gamerules entities shouldn't have more than one existing at a time, they're not really supposed to be spawned. Not sure what mapbase did there.

Portal gamerules crash nothing.

**Comment by MyGamepedia** [comment]
Also in Mapbase `hl2_gamerules` not crash the game. It's usefual for spawn sometimes if need to change some gamerule for quick test.

**Comment by MyGamepedia** [comment]
> Also in Mapbase `hl2_gamerules` not crash the game. It's usefual for spawn sometimes if need to change some gamerule for quick test.

This is also why I recommend to do this https://github.com/StrataSource/Portal-2-Community-Edition/issues/1378.

**Comment by AWildErin** [comment]
> Also in Mapbase `hl2_gamerules` not crash the game. It's usefual for spawn sometimes if need to change some gamerule for quick test.

In mapbase maybe, but the entity literally has no IO or anything in stock Source.

**Comment by pivotman319-owo** [comment]
> > Also in Mapbase `hl2_gamerules` not crash the game. It's usefual for spawn sometimes if need to change some gamerule for quick test.
> 
> This is also why I recommend to do this #1378.

Mapbase has _nothing_ to do with P2CE.

**Comment by MyGamepedia** [comment]
> Mapbase has _nothing_ to do with P2CE.

P2CE use Mapbase features.

**Comment by AWildErin** [comment]
> > Mapbase has _nothing_ to do with P2CE.
> 
> P2CE use Mapbase features.

We have a few things from mapbase, but it's mostly internal stuff (ent_create auto complete is one of them I think). We don't have any entities or features from mapbase. Having this entity not crash when spawning is not useful to fix since you're not meant to be spawning it.
