### ISSUE TITLE
ent_create portal_base2d cause game crash

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1379]
### Describe the bug

If create `portal_base2d` thanks `ent_create portal_base2d` - game get crash with this message.

![Desktop Screenshot 2023 06 16 - 18 06 12 60](https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/973dbc09-74f3-4457-b988-e434fba64b13)

### Issue Map

Any.

### To Reproduce

1. Open any map.
2. Enter in console `sv_cheats 1; ent_create portal_base2d`.
3. Pay attention to error message and that game is stoped now.

### Operating System

Any.

**Comment by AWildErin** [comment]
You're not meant to be spawning this entity yourself.

**Comment by MyGamepedia** [comment]
> You're not meant to be spawning this entity yourself.

`npc_combine` also, lol.

**Comment by MyGamepedia** [comment]
> > You're not meant to be spawning this entity yourself.
> 
> `npc_combine` also, lol.

but crash that cause it fixed.

**Comment by AWildErin** [comment]
Okay? What do you mean?

**Comment by AWildErin** [comment]
What does that have to do with this issue? For one spawning portal_base2d doesn't even crash the game, you get an engine error. And two, you're literally not meant to be spawning these entities, not every entity is designed to be spawned by the player. Sometimes they are spawned by other entities (`trigger_portal_button`), are designed for a specific purpose (`hl2_gamerules`) or are designed to be the base of other entities (`npc_combine`, `portal_base2d`). Please just stop spawning random entities, if it's an entity that is actively used in gameplay and it crashes on spawn then feel free to report it, but none of the entities I listed above are designed to be spawned by ent_create or in hammer.
