### ISSUE TITLE
npc_portal_turret_floor can't be picked up with mega gravity gun

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1385]
### Describe the bug

Attempting to pick up a turret with the super gravity gun causes it to create frozen nonsolid duplicates of itself, and not actually be picked up.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/fde189b6-394f-4706-b0b7-0542af7a9aaf

### Issue Map

Any.

### To Reproduce

1. Open map `sp_a2_turret_intro`.
2. Enter in console `sv_cheats 1; give weapon_physcannon; physcannon_mega_enabled 1; phys_swap`.
3. Try to grab turret.

### Operating System

Any.

**Comment by AWildErin** [comment]
This is fixed in staging

**Comment by MyGamepedia** [comment]
> This is fixed in staging

What about `npc_security_camera` ?
