### ISSUE TITLE
npc_turret_floor can't be picked up with mega gravity gun

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1388]
### Describe the bug

Attempting to pick up a combine turret with the super gravity gun causes it to create frozen nonsolid duplicates of itself, and not actually be picked up.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/a5e9d839-5f9b-4e51-a61f-5fe72be835ed

### Issue Map

Any.

### To Reproduce

1. Open any map.
2. Enter in console `sv_cheats 1; give weapon_physcannon; physcannon_mega_enabled 1; phys_swap; ent_create npc_turret_floor`.
3. Try to grab combine turret.

### Operating System

Any.

**Comment by AWildErin** [comment]
#1385 They use the same class, this is already fixed.
