### ISSUE TITLE
Remove npc_hover_turret

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1394]
### Which component should be improved?

Gameplay

### Describe your suggestion

Thanks [this](https://github.com/StrataSource/Portal-2-Community-Edition/issues/451) I see that team will not do any fixes or enhancements for it, even crash fixes.
This npc is very highly unstable, often cause crashes and other errors, because of this no one use it in maps or mods (if not include [this test map](https://steamcommunity.com/sharedfiles/filedetails/?id=2002720023)). This is not hard to recreate it thanks VScripts, especially in P2CE.
On it own this npc is unfinished, it have no model in game and his laser can't go through portals, his laser also have some visual peoblems.
Eventually we get that this npc is absolutely useless and rather harms the game.
These are just the main reasons why it's should be removed in P2CE. If someone will have need to have hover turret as separate entity class (this is unlikely) - recreate of it thanks AngleScripts should be easy. 

![maxresdefault (4)](https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/05d2d39c-4991-4a45-900c-f7569564aa7c)

**Comment by Luke18033** [comment]
I was thinking maybe we should keep this since it is in vanilla retail Portal 2, but it's probably too buggy to really be useful, even for like PEE2 I think we'd end up just replicating it in scripting anyway

**Comment by MyGamepedia** [comment]
> I was thinking maybe we should keep this since it is in vanilla retail Portal 2, but it's probably too buggy to really be useful, even for like PEE2 I think we'd end up just replicating it in scripting anyway

Think that with good testing should be possible to fix all problems, but I'm not very good know this npc for testing of it, but think that I anyway will research for problems of it later.

**Comment by JJL772** [comment]
We ended up doing this back in February, forgot to close this :)
