### ISSUE TITLE
npc_hover_turret cause crash if pick up it in multiplayer

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1395]
### Describe the bug

This also relevant to `Portal 2`.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/960fe4c9-b107-4041-b49c-7e36ac9c590b

### Issue Map

Any in multiplayer.

### To Reproduce

1. Open any map in multiplayer.
2. Enter in console `ent_create npc_hover_turret`.
3. Try to pick up it.
4. YOU ARE NOT IN GAME!!!

### Operating System

Any.

**Comment by AWildErin** [comment]
Hover turret will be removed when scripting comes along so none of these issues will be fixed.
