### ISSUE TITLE
Bug: Input Hooks do not get called

### ISSUE THREAD

**Issue by ENDERZOMBI102** [StrataSource/Portal-2-Community-Edition#1399]
### Describe the bug

[Input hooks](https://developer.valvesoftware.com/wiki/VScript_Fundamentals#Input_Hooks) are a way to, well, hook input before they are delivered to the entity, and can veto their passing based on a script's code.
To use one, assign a script with a `Input$InputName` function to an entity, when `InputName` is received by the entity, the `Input$InputName` function gets called, if it returns `true`, the input is sent to the entity's engine code, else the input should be discarded.

This does not happen, the `Input$InputName` function is never called.

### Issue Map

[input_hooks_test_map.zip](https://github.com/StrataSource/Portal-2-Community-Edition/files/11857820/input_hooks_test_map.zip)

### To Reproduce

1. Open map
2. Press button
3. If message "this should not print" pops up, input hooks didn't work

**Comment by Luke18033** [comment]
I just used this earlier today and it seemed to work fine?

**Comment by Luke18033** [comment]
You aren't supposed to include the `$` in the function name, not sure why you added that. It should just be for example `InputSendMsg`

**Comment by Luke18033** [comment]
When I ran this it started blocking the input, so this seems to be working fine
`ent_fire console runscriptcode "function InputSendMsg() {return false}"`

**Comment by ENDERZOMBI102** [comment]
> You aren't supposed to include the `$` in the function name, not sure why you added that. It should just be for example `InputSendMsg`

the $ was to denote that it should be replaced with the input name

**Comment by Luke18033** [comment]
Well, in your example map you literally called the function `Input$SendMsg`, and that's why it wasn't working
