### ISSUE TITLE
Hover turret laser can't go through portals

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1402]
### Describe the bug

Probably wasn't ever programmed. Think that for better compatibility with `Portal 2` mods and maps should be property and input that enable and disable opportunity to go through portals for laser. Property `Is laser can go through portals ?` yes or no. Input `PreventLaserToGoThroughPortals` value 1 or 0.

![bandicam 2023-06-25 11-46-27-013](https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/1e2e679b-b6ee-4a82-9bad-1bd398dc603e)

### Issue Map

Any.

### To Reproduce

1. Open any map.
2. Enter in console `sv_cheats 1; impulse 101; ent_create npc_hover_turret`.
3. Place to linked portals.
4. Pay attention that when hover turret attack player through portals laser just not go through portals.

### Operating System

Any.

**Comment by AWildErin** [comment]
Hover turret will be removed when scripting comes along so none of these issues will be fixed.
