### ISSUE TITLE
Barnacle incorrect work with `npc_personality_core`

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1409]
### Describe the bug

1. Barnacle not raises tongue if touch `npc_personality_core`, unlike `npc_turret_floor`. 

`npc_personality_core`.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/3aedbb4d-9cff-436f-97c5-077c3699f8bd

`npc_turret_floor`.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/5f5c83f1-04bc-49e3-84ba-544dcd8eca3e

2. Barnacle can eat `npc_personality_core` if player hold it.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/ff7eab45-e644-4e98-9901-aefe51b5c77a

3. Player not drop `npc_personality_core` if barnacle grab it.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/7d37bf08-4cc2-4e6f-bf08-00a11090c1e7

4. `npc_personality_core` disappear when barnacle bite it.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/f52a388e-87ea-4ad8-8a26-2e8ab125db2c

### Issue Map

Any.

### To Reproduce

1. Open map `d1_canals_01a`.
2. Create `npc_personality_core` under barnacle tongue thanks `sv_cheats 1; ent_create `npc_personality_core`.
3. Test it like in the videos.

### Operating System

Any.

**Comment by Luke18033** [comment]
There are actually 2 issues here, one is that it behaves wrong with viewmodel grabbed objects (Cores use viewmodel grabbing by default) and the other is that the barnacle still tries to eat Portal NPCs. I'm just going to reorganize all of these reports.

**Comment by Luke18033** [comment]
Split into #1413 and #1414
