### ISSUE TITLE
Bug: Hover turret falls through ground if get health 0

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1417]
### Describe the bug

If hover turret get health 0 - it's falls through world. Not matter how it's get health 0.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/02181d15-304e-44f9-9d81-5f441f6bbb1b

### Issue Map

Any.

### To Reproduce

1. Open any map.
2. Enter in console `sv_cheats 1; ent_create npc_hover_turret; ent_fire npc_hover_turret sethealth 0`.
3. Pay attention that it's falls through ground.

### Operating System

Any.

**Comment by AWildErin** [comment]
Hover turret will be removed when scripting comes along so none of these issues will be fixed.

**Comment by MyGamepedia** [comment]
> Hover turret will be removed when scripting comes along so none of these issues will be fixed.

Luke and craftablescience said to me that `believe some in development mod(s) rely on this entity`, but okay, I earlier suggest to remove it anyway.

**Comment by AWildErin** [comment]
I checked internally before responding to this, so it's confirmed that we're going to remove this eventually.
