### ISSUE TITLE
Bug: r_farz -1 represents too small value

### ISSUE THREAD

**Issue by Electrodynamite12** [StrataSource/Portal-2-Community-Edition#1419]
### Describe the bug

r_farz -1 seem to be equivalent to values around 1000 in p2ce (its much further in p2) so the far clipping plane is too close on maps with no fog controllers.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/57415598/37c1362a-a026-44bd-b0d2-3357c929cb98

### Issue Map

Any map without fog controller

### To Reproduce

1. Open map without fog controller
2. Make sure r_farz is set to -1
3. Go far enough (approximately 1000 units away from the target)

**Comment by SCell555** [comment]
Without fog controller, max render distance is based on size of map bounds. This is not a bug. There is similar issue already open in engine repo [github.com/StrataSource/Engine/781](https://github.com/StrataSource/Engine/issues/781) about it not accounting for recursive portals.
