### ISSUE TITLE
Bug: `SendToConsole` crashes the game

### ISSUE THREAD

**Issue by ENDERZOMBI102** [StrataSource/Portal-2-Community-Edition#1438]
### Describe the bug

Running `SendToConsole( "clear; echo running" );` in quick succession somehow crashes the game

### Issue Map

Not related to specific map

### To Reproduce

1. Execute the above script multiple times
2. Crash

**Comment by Luke18033** [comment]
Can't reproduce when using the `script` command

**Comment by ozxybox** [comment]
This may have been fixed. @ENDERZOMBI102 can you try this again?

**Comment by ENDERZOMBI102** [comment]
sure, will check after finishing dinner, which branch?

**Comment by ENDERZOMBI102** [comment]
seems to be working fine on nightly now!

**Comment by ozxybox** [comment]
Fantastic! Thank you for testing!
