### ISSUE TITLE
`env_flare` flare never go through portals

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1447]
### Describe the bug

↑. You can find it in some `Half Life 2` and episodes maps. This also in `Portal`.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/deaa5ea8-11fe-497a-9d0d-00c93d963af8

### Issue Map

Any with `env_flare`.

### To Reproduce

1. Open my map for quick test. [flare_test.zip](https://github.com/StrataSource/Portal-2-Community-Edition/files/12001991/flare_test.zip)
2. Place portal under `env_flare`.
3. Press button to launch it.
4. Pay attention that it's don't go through portals.

### Operating System

Any.

**Comment by AWildErin** [comment]
In future, could you group issues like these? It'd really be easier for both you and the developers. Easier to track 1 issue than 2 which relate to the same entity having issues with portals..

**Comment by MyGamepedia** [comment]
Okay.
