### ISSUE TITLE
Bug: +slowtime is not cheat protected

### ISSUE THREAD

**Issue by Trico-Everfire** [StrataSource/Portal-2-Community-Edition#1452]
### Describe the bug

+slowtime is a console command that allows you to slow down time, it's currently not cheat protected and can be used anywhere whenever.

### Issue Map

sp_a2_triple_laser

### To Reproduce

1. open map.
2. open console.
3. +slowtime
4. you are slowed down even without sv_cheats 1.

**Comment by Luke18033** [comment]
It shouldn't be cheat protected, you can turn it off by having an `env_global` set `slowtime_disabled = 1` - probably that should be inverted so maps need to explicitly enable it instead.

**Comment by ozxybox** [comment]
Fixed by @craftablescience in the next staging build
