### ISSUE TITLE
Bug: r_drawviewmodel doesn't reset on game restart (value is archived).

### ISSUE THREAD

**Issue by Rip-Rip-Rip** [StrataSource/Portal-2-Community-Edition#1468]
### Describe the bug

In standard Portal 2, if I was to set r_drawviewmodel to 0 then restart my game, it would be set back to 1, however in P2CE the value is archived. I'm not sure if this is intended or not, but it is a difference to the original game so I'm putting it here :)

### Issue Map

N/A, happens across the whole game.

### To Reproduce

1. Open Console
2. Type "r_drawviewmodel 0" into the console.
3. Restart game.
4. Load a map of somekind
5. Observe that the model is still hidden and that the value for "r_drawviewmodel" is still set to 0.

### Operating System

Windows 11 Build 22621.1992

**Comment by craftablescience** [comment]
Looks like this is actually intended behavior, going to leave it as-is for now
