### ISSUE TITLE
Vscript functions to access vgui panel elements

### ISSUE THREAD

**Issue by StefanH-AT** [StrataSource/Portal-2-Community-Edition#148]
Add vscript functions to manipulate position, text, visibility and other properties of vgui panels on a vgui_screen for example

**Comment by ENDERZOMBI102** [comment]
Maybe add capability of _creating gui_ too?

**Comment by Luke18033** [comment]
Kind of unrelated, but is there any sort of `panorama_screen` entity/could one be added?

**Comment by ozxybox** [comment]
Closing in favor of in world panorama #634
