### ISSUE TITLE
Bug: Turret does not see player through portals at certain distance from linked portal

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1494]
### Describe the bug

For some reason turret does not see player and other targets through portal at certain distance from linked portal, respectively can't shoot. I don't know if this work with other NPCs or not, probably should. You can also repeat this in `Portal` and `Portal 2`.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/df6b45fa-4357-46c7-aaf8-534fbcbfe09e

### Issue Map

`Portal` campaign, `Portal 2` campaign, mods that use portalgun and turrets, any technically.

### To Reproduce

1. Open map `sp_a2_turret_intro`.
2. Place two linked portals.
3. Place a turret close to portal.
4. Check if turret see you.

### Operating System

Any.

**Comment by ozxybox** [comment]
As silly as this may look, this is intended for gameplay reasons. Closing as not planned.

**Comment by MyGamepedia** [comment]
> As silly as this may look, this is intended for gameplay reasons. Closing as not planned.

Can you tell me what gameplay reasons?
