### ISSUE TITLE
Enhancement: Replace `QPhysics` to `VPhysics` for weapon shells

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1503]
### Which component should be improved?

Other

### Describe your suggestion

Like in `GoldSource` - `Source Engine` use `QPhysics` for weapon shells, it's cheap and `Valve` wasn't ever need to change it. But in P2CE we have **_portals_**, that don't interact with shells because of this. Would be nice to replace `QPhysics` to `VPhysics` for weapon shells, in addition to interacting with portals this will also solve another problem  - shells not collide with dynamic part of world (physics props, `prop_dynamic`, NPCs, other).

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/5233c918-1465-48d6-b005-76e2e668436f

**Comment by JJL772** [comment]
I dont think this is ever going to be implemented

**Comment by MyGamepedia** [comment]
> I dont think this is ever going to be implemented

is it hard ? I know that it doesn't affect gameplay, but it looks like bullshit

**Comment by AWildErin** [comment]
Hard? I have no clue, but it's not worth spending time on such a minor detail. So I'm with JJ on this, it likely will not get implemented.

**Comment by JJL772** [comment]
Not planned for now

**Comment by MyGamepedia** [comment]
Now officially: no complitible Half Life 2 with portals in Portal 2: Community Edition.

**Comment by JJL772** [comment]
> Now officially: no complitible Half Life 2 with portals in Portal 2: Community Edition.

The HL2 stuff is extremely low priority for us right now. We need to make serious cutbacks to our workload to get this game shipped. While I agree that it'd be cool to have shell casings interact with portals properly, it's so far out of scope for our team right now. I can't see it being implemented anytime soon, or ever, which is why I decided to close it.

**Comment by MyGamepedia** [comment]
I understand, but I'm probably upset anyway.
