### ISSUE TITLE
Bug: Game Crash On Laser-Triggered Cube Respawn

### ISSUE THREAD

**Issue by OrinjiNeko** [StrataSource/Portal-2-Community-Edition#1510]
### Describe the bug

When redirecting a laser through a cube into a catcher which in turn respawns the cube, the game crashes suddenly. (apparently the crash log indicated something related to the particle system?)
This makes quite a few puzzles in Aperture: Salt Mines unplayable!

### Issue Map

https://www.mediafire.com/file/6assta1gfpa2xfl/test_lasercrash.bsp/file

### To Reproduce

1. Open .bsp provided
2. Pick up cube
3. Aim at laser catcher
4. Experience the crash

**Comment by ozxybox** [comment]
Fix will be in the staging branch probably tonight.
