### ISSUE TITLE
Feature: Rename Portal 1 Crosshair command

### ISSUE THREAD

**Issue by anotsospookyskeleton** [StrataSource/Portal-2-Community-Edition#1526]
### Which component should be improved?

Other

### Describe your suggestion

In P2CE there is a command that gives you the Portal 1 crosshair which is named `portalgun_crosshair_mode`. This naming convention is inconsistent with all of the other naming conventions presented in the cvars in the game. Since this command is a client togglable command and is not forced on or off by any servers I think it would be a good change to have this command be with the client (`cl`) prefix.

My suggestion would be for this command to be named `cl_portal_crosshair_style`, as a boolean value, Zero as the Portal 2 crosshair and one as the Portal 1 Crosshair. I figured that the prefix `cl_portal` would be a good addition to the command named `cl_portal_alterate_colors` already present in the game.

Either way it's not a big deal, just something I thought about :p

**Comment by MyGamepedia** [comment]
Think that be more useful creation of page in their wiki that will describe every new cvars that available only in P2CE and Momentum Mod.
