### ISSUE TITLE
Zombies headcrab disappears if zombie touch portal cleanser

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1529]
### Describe the bug

↑. Also for posion zombie. Available in `Portal`.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/c2cebc73-559b-46eb-9763-2ede06735c28

### To Reproduce

1. Open map `testchmb_a_10`.
2. Create one of zombies in `trigger_portal_cleanser`.
3. Force zombie attack you (for cleaner to detect zombie).
4. No baked headcrab.

### Operating System

Any.

**Comment by Luke18033** [comment]
I don't think this is going to be fixed, why would you practically ever want to do this?

**Comment by MyGamepedia** [comment]
> I don't think this is going to be fixed, why would you practically ever want to do this?

Will hl2 higher priority if will appear mods for P2CE that use portal and hl2 contents together and that will require compatibility of both games so that they can be done ?

**Comment by MyGamepedia** [comment]
> Perhaps, but also you shouldn't really be fizzling NPCs with portal cleansers, that doesn't make any sense. (Unless you're PEE2, but in that case this result is more desirable anyway because it's funnier)

The what I do in the video is just show and not practical examples, you can fill in the blanks yourself and imagine how and where these mechanics can be used.

**Comment by MyGamepedia** [comment]
Closed. Duplicate of https://github.com/StrataSource/Portal-2-Community-Edition/issues/1721.

**Comment by MyGamepedia** [comment]
.

**Comment by MyGamepedia** [comment]
.

**Comment by MyGamepedia** [comment]
Sorry for these misclicks.
