### ISSUE TITLE
P2CE trying to automatically mount sourcemod assets without me adding it to mounts

### ISSUE THREAD

**Issue by Dog0719** [StrataSource/Portal-2-Community-Edition#1549]
### Describe the bug

I believe P2CE is attempting to mount the assets from a Portal 2 sourcemod I'm working on, even though I haven't told it to mount anything? I'm not sure what's happening or how to fix it 

https://github.com/StrataSource/Portal-2-Community-Edition/assets/100389777/e7b746a8-7880-4f29-894b-db32cd8c3c3b

### To Reproduce

Unsure how to reproduce

### Operating System

Windows 11

**Comment by craftablescience** [comment]
Do you have these assets in a dlc folder in Portal 2

**Comment by Dog0719** [comment]
no, I do not

**Comment by Dog0719** [comment]
Ok I fixed it, it _was_ an issue with my dlc folders, but I never had any of those assets in them. I'm not sure where it was pulling those from

**Comment by craftablescience** [comment]
Closing as we'll eventually ship with Portal 2's content to avoid issues like this
