### ISSUE TITLE
Monster box short circuit forces player to drop held objects

### ISSUE THREAD

**Issue by vrad-exe** [StrataSource/Portal-2-Community-Edition#1576]
### Describe the bug

If `BecomeShortCircuit` is fired on a monster box, the player will be forced to drop their currently held object. It seems the intent was for frankenturrets to be force dropped when short circuiting, but this was done without checking if the frankenturret was actually the object being held in the first place.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/19228201/7e0e533c-c8d9-4a02-a047-4674947b8fe5

### Issue Map

`sp_a4_intro`

### To Reproduce

1. Open `sp_a4_intro`
2. Go to the part where GLaDOS tells Wheatley the paradox
3. Spawn in a (non-franken) cube using the console and pick it up
4. When GLaDOS says the paradox and the frankenturrets short circuit, the cube is force dropped

### Operating System

Tested on Windows 10

**Comment by AWildErin** [comment]
This is fixed in staging.
