### ISSUE TITLE
Bring back <mapname>_particles.txt

### ISSUE THREAD

**Issue by Flash4433** [StrataSource/Portal-2-Community-Edition#158]
In Portal 1, there was a feature that allowed you to pack particles inside ``.bsp`` and, with the help of a manifest file, the game would detect them. [An example of this is HMW's Try Anything Twice maps.](http://forums.thinking.withportals.com/downloads.php?view=detail&df_id=281) However, this feature was completely cut in Portal 2, as particles could only be loaded on Game Start, at least from my understanding. Being able to properly pack particles inside maps would be a nice feature to have again.

**Comment by Luke18033** [comment]
This doesn't work in P2?! Come on Valve, first `scenes.image`, now this...are you TRYING to make things hard for us?

**Comment by Flash4433** [comment]
I wonder what else we can't pack, and if P2CE can fix that...

**Comment by Luke18033** [comment]
The difference with the two things I said is that they're things we USED to be able to pack, before Valve decided to make them only load at game startup.

**Comment by Luke18033** [comment]
It's also possible that map-specific manifests weren't removed, but are now required to be in the same subdirectory as the map - in that case we still can't use it for workshop maps (since they get put in a random subfolder), but it's not totally gone either.

**Comment by Luke18033** [comment]
For P2CE, it'd probably be better to just remove the particles manifest entirely, and automatically load any PCFs placed in the `particles/` folder (first when the game starts, and whenever a map is loaded).

**Comment by CitadelCore** [comment]
The particle manifest is important for precaching. I think what we'll do is bring back the map-specific manifests.

**Comment by Luke18033** [comment]
I don't understand why you can't just handle them the same way as other things like materials?

**Comment by CitadelCore** [comment]
It _might_ be possible to implement loose PCF loading for maps, however, this wouldn't be enabled for particle systems in the base game - not preaching particles will cause performance issues on people's systems.

**Comment by Luke18033** [comment]
Been a while since I've commented here, but what I was basically suggesting is to just treat every PCF in the `particles/` folder as if it were in the manifest. That's how it'd usually end up being configured anyway.

**Comment by TeamSpen210** [comment]
That's what sounds do actually, they're force precached if in a bsp.

**Comment by Luke18033** [comment]
Is this implemented yet? Not sure if it was merged in with the rest of Josh's changes.

**Comment by Luke18033** [comment]
This should be implemented now
