### ISSUE TITLE
Feature: <Title> Laser changing color.

### ISSUE THREAD

**Issue by AshCatBoi** [StrataSource/Portal-2-Community-Edition#1582]
### Which component should be improved?

Other

### Describe your suggestion

It would be cool if the laser would change color every time it is reflected or changes direction from a cube or a portal.

**Comment by craftablescience** [comment]
You will hopefully be able to implement something like this in your own map or mod with scripting. It wouldn't be a good idea to hardcode that functionality into P2CE

**Comment by AshCatBoi** [comment]
tru. thanks for your time
