### ISSUE TITLE
Half-Life 2 Bug: Crossbow bolts incorrect work with items and weapons

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1588]
### Describe the bug

Available also in original games. This bug fixed in `Half-Life 2: Deathmatch`. This also breaks the behavior of crossbow bolts visual effects.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/00c8cca9-9e7b-4302-992a-3332ddaffe1f

### To Reproduce

1. Open any map.
2. Enter in console `sv_cheats 1; give weapon_crossbow; ent_create item_healthkit`.
3. Shoot healthkit.
4. Now crossbow bolt broken.

### Operating System

Any.

**Comment by DrPeeper228** [comment]
yeah it works exactly like in hl2 since it was literally copied from that i think

**Comment by AWildErin** [comment]
This is something we are not interested in fixing. It's a bug in stock Half Life 2 and fixing stock Half-Life 2 bugs like this is not in the scope of P2:CE.
