### ISSUE TITLE
Bug: [Hammer] Strange preview on point entities, like light_spot when duplicated from another entity

### ISSUE THREAD

**Issue by karl-police** [StrataSource/Portal-2-Community-Edition#1595]
### Describe the bug

THIS DOESN'T HAPPEN IN THE REGULAR PORTAL 2.

In general, creating any entity in P2:CE without starting with ``info_player_start`` causes issues.

But there are specific things that happen. And this one is strange.

![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/12023782/6e26dc7d-5f7f-405a-8770-a7ef7811b072)

### Issue Map

-

### To Reproduce

1. Create a ``point_spotlight``
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/12023782/da8d7371-109d-416b-8ce6-67d9969900d0)

2. Shift+Drag it to duplicate the ``point_spotlight``

3. Change the duplicated one to a ``light_spot``
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/12023782/d29bfee8-31db-4f7a-b369-1a1e791253c7)

4. It's broken
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/12023782/c68594f3-5cba-459a-bbf3-0ff8ed7a16eb)

### Operating System

Windows 10

**Comment by ozxybox** [comment]
This has been fixed internally and will be in the next update.
