### ISSUE TITLE
Bug: Building Cubemaps gives a "check for write enable error"

### ISSUE THREAD

**Issue by Lifegivesmelemons** [StrataSource/Portal-2-Community-Edition#1599]
### Describe the bug

![Screenshot (1052)](https://github.com/StrataSource/Portal-2-Community-Edition/assets/11589957/5dd6ae9e-4ee9-4abf-8350-6efbdea37392)

### Issue Map

Any (Not sure if this is just specific to the workshop test branch or not)

### To Reproduce

1. Load a map
2. Attempt to build cubemaps

**Comment by ozxybox** [comment]
This issue was fixed a while ago. Iirc it was only an issue with the workshop branch.
