### ISSUE TITLE
Bug: [Workshop Beta] `logic_choreographed_scene` custom .vcd files do not play

### ISSUE THREAD

**Issue by LambdaCore21** [StrataSource/Portal-2-Community-Edition#1601]
### Describe the bug

Bug: [Workshop Beta] Custom `logic_choreographed_scene` .vcd files do not play.

Uploading a workshop map to the new addon system causes the custom .vcd to play "fiddlesticks" instead of the .wav

This seems to be similar to #1604 

When this addon structure was first published to closed beta, the .vcd would not play correctly **on the very first** map load / game launch. However, it would play correctly for any game / map launch afterwards

### Issue Map

https://steamcommunity.com/sharedfiles/filedetails/?id=3132663480

### To Reproduce

1. Subscribe
2. Launch the workshop map "vcd_new" and get fiddlestick'd

**Comment by LambdaCore21** [comment]
After the workshop update, the situation is now worse: custom .vcd files do not play anymore

![grafik](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/dc055a61-42ad-4bf5-8ddc-91d8c688948d)

I have re-uploaded

https://steamcommunity.com/sharedfiles/filedetails/?id=3088837983

https://steamcommunity.com/sharedfiles/filedetails/?id=3088904097

to the new links

https://steamcommunity.com/sharedfiles/filedetails/?id=3124125866

https://steamcommunity.com/sharedfiles/filedetails/?id=3124126261

and still, fiddlesticks only:

![grafik](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/5fe87582-21f1-485b-becd-9126a77bc329)

**Comment by LambdaCore21** [comment]
![grafik](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/5d4b243c-f619-4815-90ab-37581125aecb)

**Comment by JJL772** [comment]
Were you able to get this working with the sound script in `scripts/sounds`?

**Comment by LambdaCore21** [comment]
It is still the same issue:

https://steamcommunity.com/sharedfiles/filedetails/?id=3132663480

As soon as I put these exact files into the P2CE custom folder, it works like a charm. Files attached

[vcd test.zip](https://github.com/StrataSource/Portal-2-Community-Edition/files/13848461/vcd.test.zip)

**Comment by JJL772** [comment]
Turns out I forgot to reload sound scripts when content is reloaded :)
Easy fix, will be in the next build tomorrow.

**Comment by LambdaCore21** [comment]
Friggin' epic! 😁

**Comment by JJL772** [comment]
Completed in workshop beta branch
