### ISSUE TITLE
Issue: [Workshop] particles_manifest.txt don't combine or add onto the mount

### ISSUE THREAD

**Issue by karl-police** [StrataSource/Portal-2-Community-Edition#1604]
### Describe the bug

See this example addon:

a player is not supposed to go to the game files and add
```
"file"		"!particles/pgun_mel.pcf"
```
just to get the other particles to work

### Issue Map

-

### To Reproduce

Create an addon that has custom particles and a particles_manifest.txt
the particles_manifest.txt is used to register particles, and the issue is that they don't register because the game doesn't load or mount them, it has no implementation

**Comment by LambdaCore21** [comment]
Seems like custom particles are now fixed. I have used a custom particle .pcf and particles_manifest.txt https://steamcommunity.com/sharedfiles/filedetails/?id=3126919597

**Comment by LambdaCore21** [comment]
Seems like it is still not working ☹

**Comment by LambdaCore21** [comment]
![grafik](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/b1c50b7d-f199-43b6-bf3c-38bff0c90176)

**Comment by JJL772** [comment]
In summary, every PCF in the particles/ directory will be loaded, but *not* precached. This only applies to addons using the workshop system; mounted steam games or custom folder "addons" will not have their particles automatically loaded and must still use the manifest.

**Comment by karl-police** [comment]
uuuuhhhh

**Comment by LambdaCore21** [comment]
What happens with standard P2 particles regarding the hierarchy? Let's say I make the Laser emitter particle blue and copy it into the addon folder?
