### ISSUE TITLE
Feature: Multiple Voxel Size Selection in NEW Puzzle maker

### ISSUE THREAD

**Issue by genestrashcan** [StrataSource/Portal-2-Community-Edition#1606]
### Which component should be improved?

Gameplay

### Describe your suggestion

**Please leave this feature request open for later reference:**

This is the first of many suggestions i have for features that should be coded into the new puzzle maker that you will be coding from scratch to replace the original Perpetual Testing Initiative Puzzle Maker when the time comes.

In the original PETI puzzle maker there was only 1 size of voxel you could select to make test chamber geometry as seen in this image:

![Basic_Map_PeTI_Portal_2](https://github.com/StrataSource/Portal-2-Community-Edition/assets/11165643/54f746b1-1ca5-4d9d-978d-74f2c4dd1a83)

In the new puzzle maker we should be able to change the voxel size of the geometry we want to edit. The voxel sizes we should be able to change to should be the following:

1/4th - as shown in the image would make it possible to make thin walls you could put a fizzler in or a window in like what is shown in the image below.

1/2th - double the size of 1/4th.

1 - the original selection size from the original PETI.

2 - double the size of x1 or 2x2 1 voxel sized panels or a single large panel.

The following image below from test chamber 9 of the original first portal game is used to show and explain what i mean:

![voxel example](https://github.com/StrataSource/Portal-2-Community-Edition/assets/11165643/301ef7bd-3a69-4ec1-8a14-2b853b32d5a0)

Also there should be a way (from a drop down menu or something similar) to change the PANEL SIZE TEXTURE of the face of the voxel you have selected in the new puzzle maker. This would let us be able to change the textures used on a 1/4 voxel thick wall to give it some more variance like the 1/2 x 1/2 voxel sized panels you see on both sides to the hole above the fizzler in the image above.

**Comment by Luke18033** [comment]
We don't need issues being opened for the puzzlemaker right now, it's not anywhere close to being worked on yet
