### ISSUE TITLE
Fog inconsistency in sp_a1_wakeup

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1613]
### Describe the bug

In `sp_a1_wakeup`, the silhouette models that surround GLaDOS' chamber are not faded into the fog as much as they should be, making them look much more out of place. Unsure if this is a difference in the fog rendering or the material itself.

Portal 2:
![portal2_pDSCdSAJqG](https://github.com/StrataSource/Portal-2-Community-Edition/assets/19228201/595c896c-6bc5-42b5-b064-c2f5e3085f66)

P2CE:
![chaos_yud2n6XNNr](https://github.com/StrataSource/Portal-2-Community-Edition/assets/19228201/6abe910d-fde0-4ee2-828e-a9405adf7eef)

### To Reproduce

Self explanatory

### Operating System

Tested on Windows 10

**Comment by JJL772** [comment]
Done
