### ISSUE TITLE
Half-Life 2 Bug: Strange behavior of RPG if player use vehicle before rocket-propelled grenade explodes

### ISSUE THREAD

**Issue by MyGamepedia** [StrataSource/Portal-2-Community-Edition#1616]
### Describe the bug

Viewmodel don't disappear, laser point too.
Also in original `Half Life 2`. Fixed in `Half Life 2: Deathmatch` (however the RPG laser beam is still buggy).
P2CE.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/a0779002-427e-4bbc-99dd-a5d8895608df

`Half Life 2: Deathmatch`.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/131fc19b-ec8d-44fb-8b61-cef818a7a005

### To Reproduce

1. Open `d2_coast_05`.
2. Use RPG.
3. Shoot and use vehicle before rocket-propelled grenade explodes.
4. Now RPG is broken.

### Operating System

Any.

**Comment by AWildErin** [comment]
This is not something we are interested in fixing. We accept HL2 bugs if they break compatibility with Portal 1, this doesn't break compat at all.

**Comment by MyGamepedia** [comment]
> This is not something we are interested in fixing. We accept HL2 bugs if they break compatibility with Portal 1, this doesn't break compat at all.

Will I be able to fix things like this with AngleScripts?

**Comment by AWildErin** [comment]
Given it lies directly within the rpg code, chances are no. Mixin support for AS would be awesome, but we realise that so much would have to go into it that it's not feasible on our end.

**Comment by MyGamepedia** [comment]
> Given it lies directly within the rpg code, chances are no. Mixin support for AS would be awesome, but we realise that so much would have to go into it that it's not feasible on our end.

It turns out that if I need to fix this - I will need to write weapon_rpg from scratch.
