### ISSUE TITLE
Feature: Add support for logic_movieplayer to play videos with format .bik (for backward compatibility) and .mp4

### ISSUE THREAD

**Issue by rabbix2020** [StrataSource/Portal-2-Community-Edition#1627]
### Which component should be improved?

Entity

### Describe your suggestion

I suggests add support of these because it could make life of mapper easier and make compatibility with more portal 2 maps.

**Comment by AWildErin** [comment]
`.bik` support was purposely removed, webm is the intended format you're meant to be using. You can convert from bik to webm using ffmpeg
