### ISSUE TITLE
Workshop Bug: All particle systems use strange materials

### ISSUE THREAD

**Issue by LambdaCore21** [StrataSource/Portal-2-Community-Edition#1644]
### Describe the bug

![1a](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/363ad3d4-9d74-403b-9ae6-c46012731d69)

![1b](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/7f19679f-8a07-4f54-855c-c417fd3c61d3)

![1c](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/ee4fd544-124d-4a62-9889-595cc268c6e9)

![1d](https://github.com/StrataSource/Portal-2-Community-Edition/assets/63379443/f9f6bc43-dd93-4a74-ace8-47109d0aab0f)

### Issue Map

Any standard Portal 2 map with particles

### To Reproduce

Play Portal 2 campaign, for example a4 bossfight

**Comment by JJL772** [comment]
Fixed last week.
