### ISSUE TITLE
Bug: Using the Staging (Unstable) Branch, base texture not showing up on PBR materials

### ISSUE THREAD

**Issue by JackRHainsworth** [StrataSource/Portal-2-Community-Edition#1648]
### Describe the bug

Base texture doesn't show up on pbr materials in the unstable branch, after lighting gets fixed. Base texture just shows up as black. The rest of the material's textures (mrao and bump) work fine.

EDIT: This also happens in hammer, not just in game.

### Issue Map

My styleguide map.

### To Reproduce

Create a PBR material and place it in the level.

**Comment by JJL772** [comment]
Can you attach your VMT and textures here?

**Comment by JackRHainsworth** [comment]
[stylised_metal.zip](https://github.com/StrataSource/Portal-2-Community-Edition/files/14393706/stylised_metal.zip)
These textures so in materials/stylised_metal

**Comment by tsa96** [comment]
Your VMF is broken, don't use relative paths like that.

**Comment by JackRHainsworth** [comment]
> Your VMT is broken, don't use relative paths like that.

If this was the case, wouldn’t he base texture show as pink and black check? Or wouldn’t the bump and reflection textures also not work?
