### ISSUE TITLE
Bug: Wheatley's Flashlight did not turn on

### ISSUE THREAD

**Issue by Wolfcl0ck** [StrataSource/Portal-2-Community-Edition#1649]
### Build Information
**Chaos.exe Build Date:** 06-11-2023 22:13:42 UTC
**Server Build Date:** 06-11-2023 22:24:40 UTC
**Client Build Date:** 06-11-2023 22:24:41 UTC
**Branch:** Default, using Panorama UI

### Hardware Information
**CPU:** AMD Ryzen 9 3900X 12-Core Processor 3.80 GHz
**GPU:** 4095MB NVIDIA GeForce RTX 2070 (EVGA)
**RAM:** 32 GB DDR4 RAM, 2x 16 GB Corsair

### Bug Information
the env_projectedtexture that is supposed to appear coming off of Wheatley's eye did not appear. Associated sprites and light glows _did_ appear.

### Additional Potential Factors
"cl_portal_crosshair_mode" was set to 1
Game is running in Borderless Windowed mode
Game is running with -multirun enabled
Game is running with -insecure enabled

### Footage
![20240224130441_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/16748747/98a5cde8-2e13-45fd-9b52-114dec0be1a8)
![20240224130856_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/16748747/6551fad0-8ad3-447c-a82b-8fbb7c42575d)

### Issue Map

sp_a2_bts3
sp_a2_bts4

### To Reproduce

1. Open one of the associated maps
2. Activate trigger that causes Wheatley to turn on his flashlight (if applicable)

### Operating System

Windows 10 Home 64-bit, build 19045.3570

**Comment by ozxybox** [comment]
This issue was fixed on the Steam branch “unstable”.
