### ISSUE TITLE
Enhancement: Bigger font size for developer console

### ISSUE THREAD

**Issue by HugoBDesigner** [StrataSource/Portal-2-Community-Edition#1660]
### What would this enhancement be for?

UI/UX

### Describe your enhancement suggestion in more detail

When running the game from Hammer, a developer console opens with it (presumably a vgui leftover). However, that console is far more readable and accessible than the main one, especially with regards to font size. It'd be great if the default font size for the console could be increased.

![image](https://github.com/StrataSource/Engine/assets/6296061/39a58403-8559-4617-bb4b-434916429012)
`Left: main, toggleable console. Right: old console, more readable`

**Comment by craftablescience** [comment]
This was completed
