### ISSUE TITLE
Feature: prop_weighted_cube outputs for being placed on a button, or otherwise activated

### ISSUE THREAD

**Issue by Wheattttt** [StrataSource/Portal-2-Community-Edition#1665]
### Which component should be improved?

Entity

### Describe your suggestion

Outputs for whenever a cube is powering something (pretty much exclusively when their orange skin would be normally switched to) would be very useful for custom cube types, as currently it is much more complicated to get working skins for custom cube types. I can also imagine some other, though admittedly more niche uses for such outputs.

**Comment by JVGRYT** [comment]
Ooh, I look forward to using this :3
Thankyouu!
