### ISSUE TITLE
Feature: Crosshair scale cvar

### ISSUE THREAD

**Issue by Badpoolinator** [StrataSource/Portal-2-Community-Edition#1669]
### Which component should be improved?

Render

### Describe your suggestion

In Portal: Revolution, there is a cvar to scale the crosshair. (portalgun_crosshair_scale) It would be nice if this was added to P2CE.

**Comment by JJL772** [comment]
Done in next staging build. Although I called it `cl_portal_crosshair_scale` for consistency with the other portal crosshair cvar
