### ISSUE TITLE
Half-Life 2 Bugs: lotta stuff

### ISSUE THREAD

**Issue by MarcusKubis9** [StrataSource/Portal-2-Community-Edition#1671]
### Describe the bug

Jeep has weird FOV when driving fast, Airboat is tilted forward in water

vehicles make you look in a random direction (as seen in jeep and airboat videos)

when you give yourself the pistol/shotgun you are not given any ammo for them

Reflections sometimes get buggy... its hard to explain

shooting the revolver while on adhesion gel fucks with your camera

because the video is too big and I can't be bothered I compiled all the bugs into an unlisted youtube video
https://youtu.be/lJvV4ABHXps

### To Reproduce

Jeep:
Go to any map with the Jeep and drive around or get in/out of it

Airboat:
Go to any map with the Jeep and drive around in water or get in/out of it

weapon ammo bug:
Go to any map and type "give weapon_pistol" "give weapon_shotgun", then go into console and type "use weapon_pistol" "use weapon_shotgun", if nothing happens you recreated the bug, if you want to use the weapons try "give item_ammo_pistol" or "give item_box_buckshot"

revolver adhesion gel:
go to any map and enable paint, give yourself the paint gun and upgrade it. paint a wall and ceiling with adhesion gel and give yourself "weapon_357", then walk on the adhesion gel and shoot

**Comment by AWildErin** [comment]
It would be appreciated if these could be made into their own issues. It makes it easier for us to track it that way

**Comment by MarcusKubis9** [comment]
> It would be appreciated if these could be made into their own issues. It makes it easier for us to track it that way

Yeah I can do that

**Comment by AWildErin** [comment]
Thank you for doing that! I'll close this issue now since those were made
