### ISSUE TITLE
Bug: VGUI console shows when using Panorama and launching game with -console

### ISSUE THREAD

**Issue by ddddpplo** [StrataSource/Portal-2-Community-Edition#1672]
### Describe the bug

When you launch the game with -console, the VGUI console shows up on the loading screen and doesn't disappear on map load, even when the game isn't paused. Sometimes if you pause you can get both the pano and VGUI consoles showing on top of each other. Pressing the toggle console key twice will hide it though.

Side note: Launching with -console probably doesn't have much purpose, but it was in my default hammer map launcher config. A really easy solution is probably to just not launch with -console

### Issue Map

Any map

### To Reproduce

1. Launch game without -legacyui and with -console

**Comment by craftablescience** [comment]
Just editing a bit for clarity, it's not called the quake console

**Comment by ddddpplo** [comment]
> Just editing a bit for clarity, it's not called the quake console

Ah okay, I'd seen it called the quake console in p2ce's settings menu so I figured that's what the devs called it lol.

**Comment by JJL772** [comment]
Yeah that was in reference to a quake-like drop down console mode we used to have. It was never brought over from our original Panorama code though

**Comment by JJL772** [comment]
Fixed in next staging build
