### ISSUE TITLE
Half-Life 2 Bug: Airboat is tilted forward in water

### ISSUE THREAD

**Issue by MarcusKubis9** [StrataSource/Portal-2-Community-Edition#1674]
### Describe the bug

title

might be worth trying loading into a map where the airboat doesn't start in the water

https://www.youtube.com/watch?v=lJvV4ABHXps&t=1s

### To Reproduce

Go to any map with the Airboat and drive around in water

**Comment by craftablescience** [comment]
Duplicate of #1416
