### ISSUE TITLE
Bug: prop_tractor_beam is missing option for skin

### ISSUE THREAD

**Issue by Wheattttt** [StrataSource/Portal-2-Community-Edition#1679]
### Describe the bug

This is a mild inconvenience at worst, but the `prop_tractor_beam` entity is missing a keyvalue for changing the model's skin in the FGD. Adding the keyvalue yourself via smart edit or setting it via the `Skin` input works, but is slightly more tedious.

### Issue Map

N/A - Problem occurs with an entity in the P2CE FGD.

### To Reproduce

1. Open Hammer
2. Create a `prop_tractor_beam`
3. There is no `Skin` keyvalue

**Comment by Equalizer5118** [comment]
Made a pr in the fgd [here](https://github.com/StrataSource/FGD/pull/218)

**Comment by Equalizer5118** [comment]
Is there a rusted version in the base game
