### ISSUE TITLE
Bug: Compiler freezes at "0 Seconds Elapsed" 

### ISSUE THREAD

**Issue by whytomake** [StrataSource/Portal-2-Community-Edition#1686]
### Describe the bug

Whenever I compile my map, or literally any map, it gets stuck at "0 seconds elapsed", a workaround is to compile the map in the default portal 2 hammer editor, but you're missing out on the p2ce exclusive 

### Issue Map

Quite Literally every map.

### To Reproduce

1. Open a Map
2. Compile the Map
3. It will probably get stuck at "0 seconds elapsed"

### Operating System

Windows (since thats what I'm using)

**Comment by AWildErin** [comment]
Please post more info, I can't replicate this on the map I tried. 

What compile options are you using, what exactly is it being stuck on, did you try other maps?

**Comment by whytomake** [comment]
I've tried this on sp_a4_tb_wallbutton, my own maps (helpme.vmf and test1), 
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/127506430/ca3543af-2d93-4e8e-b5c4-6be15695ab4d)
This is the compile setting i use on normal,
![image](https://github.com/StrataSource/Portal-2-Community-Edition/assets/127506430/cbe210d7-ff17-43ca-bce9-2aefa697ffbf)
this is the compile settings i use on expert, just so you know i also run it on fast

**Comment by AWildErin** [comment]
And this happens on every map? Even a vmf with just a box and info_player_start? I still can't replicate this on the map I'm trying it with. Can you post the full compile log?

**Comment by whytomake** [comment]
I've ran the compiler, i dont know what I did but it works now, so im closing this issue
