### ISSUE TITLE
Untie music volume from game volume

### ISSUE THREAD

**Issue by StefanH-AT** [StrataSource/Portal-2-Community-Edition#169]
Music volume seems to be a multipliar of the game volume so you can never play the game with music without getting earraped by doors and buttons which are loud af

**Comment by creative-collective** [comment]
Music volume is a multiplier of game volume, but only to things like soundscripts and ambient_generics which have a file tagged with a pound sign (#) at the start to designate that sound as music. 
Untying the two would be either far too time consuming or impossible outright.
If you are having issues with the sound of doors and buttons, I would look into those soundscripts.

**Comment by SpyceTewan** [comment]
What I'm saying is that the music volume gets turned down as the master volume gets lower. I' suggesting to make the music volume independent of the master volume and keep it unaffected from the master vol.

**Comment by Konclan** [comment]
Master should affect all sounds, what I would suggest is splitting game sounds into its own slider. Also possibly add a VO slider? (I would greatly appreciate one)

**Comment by SpyceTewan** [comment]
Yes i think that's be the best approach. Sorta like minecraft has it
