### ISSUE TITLE
Bug: Crosshair does not scale properly

### ISSUE THREAD

**Issue by Badpoolinator** [StrataSource/Portal-2-Community-Edition#1697]
### Describe the bug

If you use `cl_portal_crosshair_scale` while holding a portal gun, only the portal indicators scale. The 5 dots do not scale at all. The indicators will scale around their respective centres, instead of around the centre of the crosshair.

![Screenshot 2024-07-17 173500](https://github.com/user-attachments/assets/0d465dc0-fe23-4e0c-98f2-d502d3b1e35d)
![Screenshot 2024-07-17 173418](https://github.com/user-attachments/assets/b3528c13-eddd-40be-b4a4-6aa9ad1c9c16)

### Issue Map

Any

### To Reproduce

1. Make sure you are holding a portal gun
2. Set the command `cl_portal_crosshair_scale` to anything other than `1`
3. Observe

**Comment by JJL772** [comment]
Fixed in next update
