### ISSUE TITLE
Bug: Language files always load p2ce_[language].txt.

### ISSUE THREAD

**Issue by PRYZMwubs** [StrataSource/Portal-2-Community-Edition#1725]
### Describe the bug

Currently, the language files will always default to loading the prefix 'p2ce' and will not load if you attempt to use the prefix of your standalone mod or source mod instead - even after renaming chaos.exe.

<img width="958" alt="Screenshot 2024-10-12 214738" src="https://github.com/user-attachments/assets/cd0e3db1-6292-4632-9d59-31ac614c155b">

### Issue Map

The issue doesn't happen in a map, but rather in the UI.

### To Reproduce

There are two ways to see this bug in action. Here's what I first tried:

1. Rename to chaos.exe to anything, let's say 'example_mod.exe'
2. Rename the p2ce folder to 'example_mod'
3. Rename 'p2ce_english.txt' inside 'resources' to 'example_mod_english.txt'

And it does the same thing if you try using a source mod, here's what I did using the [default p2ce mod template](https://github.com/StrataSource/p2ce-mod-template) - of which I did not make any changes to when trying:

1. Add source mod to SteamLibrary/steamapps/sourcemods and drop the mod in.
2. Make sure there's a language file within the resources folder - in the template it's 'p2ce-mod-template_english.txt'
3. Go into Portal 2 Community Edition > p2ce > resource and delete 'p2ce_english.txt'

**Comment by ozxybox** [comment]
This should be fixed as of the November 14th build
