### ISSUE TITLE
Bug: Face Poser doesn't open

### ISSUE THREAD

**Issue by TwoKrazy** [StrataSource/Portal-2-Community-Edition#1732]
### Describe the bug

Face Poser crashes upon launch

### Issue Map

N/A

### To Reproduce

1. Launch `hlfaceposer`, either via the P2CE SDK launcher or a command that uses the `-game` parameter

**Comment by ozxybox** [comment]
What did you pass for -game? Did you try `../../p2ce` or an absolute path?

**Comment by craftablescience** [comment]
Launching from the SDK launcher works for me, it runs it with the current directory set to the Portal 2 Community Edition folder and passes `-game p2ce`

**Comment by TwoKrazy** [comment]
> What did you pass for -game? Did you try `../../p2ce` or an absolute path?

i dd `../../p2ce`

**Comment by TwoKrazy** [comment]
update: idk what happened, but I changed the branch to the previous version, deleted both `hlfaceposer.exe` and `hlfaceposer.rf', switched back to the unstable branch, and it suddenly worked...
