### ISSUE TITLE
Bug: P2CE has especially strong focus hold.

### ISSUE THREAD

**Issue by Trico-Everfire** [StrataSource/Portal-2-Community-Edition#1733]
### Describe the bug

P2CE specifically has such a strong focus hold. At least on Linux. P2CE will have a VERY strong hold on focus. Every other game, even other source  games gladly lose focus when I alt tab (on Linux alt tabbing is fine with source), but P2CE will force the mouse to the center of the screen in most cases. This extends to crashes as well, it will never release the mouse, even when I tab if P2CE locks up. It's very strange and I've never seen any other application do this. 

### Issue Map

N/A

### To Reproduce

Open P2CE.
Make it lose focus (alt tab is the quickest way)
Likely mouse will be forced to screen center (isn't guarenteed)

### Operating System

Linux, KDE Neon.

**Comment by JJL772** [comment]
Fixed in next update
