### ISSUE TITLE
Feature: Electricity Field

### ISSUE THREAD

**Issue by ReNardier** [StrataSource/Portal-2-Community-Edition#1747]
### Which component should be improved?

Entity

### Describe your suggestion

at the risk of sounding of dubious intelligence: given its recent appeance in the “Portal: Companion Collection”, what are the chances of the “Portal: Still Alive”'s Electricity Field being implemented?
https://theportalwiki.com/wiki/Portal:_Still_Alive
https://theportalwiki.com/wiki/Electricity_Field
![Electricity_Field_On](https://github.com/user-attachments/assets/d5cb2586-6c60-4064-9a47-7a488760b19a)

**Comment by craftablescience** [comment]
is this impossible to make with existing entities? whats stopping you from making an electricity field instance?

**Comment by MyGamepedia** [comment]
> is this impossible to make with existing entities? whats stopping you from making an electricity field instance?

Yeah, it's just trigger_hurt with some logic abd effects, nothing more.

**Comment by craftablescience** [comment]
This is out of scope of P2CE if you can make this in Hammer relatively easily. I'm sure there's a beemod UCP for it as well if you don't know how to use Hammer.
