### ISSUE TITLE
Bug: Community Test chamber menu selections dont highlight correctly

### ISSUE THREAD

**Issue by allspice101** [StrataSource/Portal-2-Community-Edition#1772]
### Describe the bug

When in the community test chambers, the selections incorrectly highlight. Aditionally, the background menu doesnt update

### Issue Map

https://github.com/user-attachments/assets/5f36378c-5359-4895-baa4-8e59498226c7

### To Reproduce

Open P2:CE without the panorama
Click on "Community Test Chambers"
Observe the UI

### Operating System

Windows 11

**Comment by JJL772** [comment]
We are not supporting the VGUI menu anymore, and the community test chambers functionality is broken due to the new workshop support.
