### ISSUE TITLE
Bug: Gel in first section of `sp_a3_crazy_box` doesn't work

### ISSUE THREAD

**Issue by TwoKrazy** [StrataSource/Portal-2-Community-Edition#1776]
### Describe the bug

When attempting to play through the map, the blue gel doesn't work on the surface that it needs to. This might be because of the surface being a `func_brush`, but I haven't tested that

[Video](https://cdn.discordapp.com/attachments/1016158143446782052/1319380650205253805/Portal_2__Community_Edition_-_DX11_Tools_Mode_2024-12-19_14-05-37.mp4?ex=6765c07b&is=67646efb&hm=97b348f24688c3e892c904c9188f383130500f252b33f7682f6cd391eab3d2ef&)

### Issue Map

sp_a3_crazy_box

### To Reproduce

1. Open the map
2. Attempt to play through it normally

**Comment by craftablescience** [comment]
It is because of the surface being a func_brush

Set the following cvars and let me know if it works:
```
traceray_force_vphysics 0
traceray_unshrink_vphysics_brushes 0
```

These will be the defaults in a future update

**Comment by allspice101** [comment]
after inputting cvars, this is the results
https://github.com/user-attachments/assets/1bef4aa5-0ee6-46cd-a8a0-31caaf55eb23

**Comment by craftablescience** [comment]
I think your file didn't upload all the way

**Comment by allspice101** [comment]
fixed
https://github.com/user-attachments/assets/1f4d9cef-e20c-4bd3-8320-0bb3e0956f37

**Comment by JJL772** [comment]
Thanks for confirming for us!
