### ISSUE TITLE
IncludeScript and script_execute fail to execute VScripts if .nut extension is not provided

### ISSUE THREAD

**Issue by vrad-exe** [StrataSource/Portal-2-Community-Edition#1781]
### Describe the bug

The `script_execute` command and `IncludeScript()` VScript functions fail when the `.nut` extension isn't provided. The code seems to attempt to append the extension, but doesn't include the dot before it, causing the file to not be found.

![image](https://github.com/user-attachments/assets/f8b6f8b7-d4d8-4788-9a31-11166b6fc66f)

This causes all Portal 2 choreo to fail and produce a bunch of console spam on map load, since it relies on IncludeScript:

![image](https://github.com/user-attachments/assets/3e0af33a-bf97-4fd1-801d-b3252d395a95)

### Issue Map

Any Portal 2 campaign map, any map if `script_execute` is used

### To Reproduce

1. Open portal 2 campaign map
2. Look at the console, there will be a bunch of script errors, preceded by the lines indicating it failed to include the scripts

### Operating System

Windows 10

**Comment by ozxybox** [comment]
oh nuts, thanks for catching this! i think this is something i broke today in the rush to get the build out...

**Comment by ozxybox** [comment]
Yup! lol. It'll get fixed in tonight's hotfix :P
Wont be any changelog for it though, as it's going to be a tiny patch

**Comment by ozxybox** [comment]
Should now be fixed!
