### ISSUE TITLE
Half-Life 2 Compat Bug: Fence model in d1_canals_01 is upside down, blocking progression

### ISSUE THREAD

**Issue by Pacca64** [StrataSource/Portal-2-Community-Edition#1788]
### Describe the bug

Partway through d1_canals_01, the player is intended to jump over a fence while being fired at by metrocops. However, for some reason, the fence, both visually and collision wise, appears upside down in P2CE which makes it significantly harder to complete the level as intended. Decompiling the map shows that the fence in the map is a very ordinary looking prop_static, however it still appears wrongly upside down in P2CEs' hammer as well. Perhaps something about the model itself is setup strangely? As someone who's primarily a mapper, I'm not entirely sure what could've gone wrong here.

HL2:
![20241222232734_1](https://github.com/user-attachments/assets/b8a6c705-6259-4bf4-927d-e8a160c15486)

P2CE:
![20241222232757_1](https://github.com/user-attachments/assets/1279205c-1581-4c6f-86e9-c0feab7e7a95)

The fences model name is 'models/props_wasteland/interior_fence004b.mdl'

### To Reproduce

1. mount HL2
2. enter the map d1_canals_01 (or just view this model, given it's upside down in hammer and likely other maps its' in)

**Comment by SCell555** [comment]
This is model from ep1 conflicting with model from hl2 game.
