### ISSUE TITLE
Hammer Bug: Vactube junction models are missing

### ISSUE THREAD

**Issue by Equalizer5118** [StrataSource/Portal-2-Community-Edition#1790]
### Describe the bug

As title states, the majority of the `comp_vactube_junction` models are missing, except for the default behaviour.
All curves and splitters are missing models, but the default model still exists.
Screenshot (default type, each after is a different type parameter):
![image](https://github.com/user-attachments/assets/8d82bbc0-0c35-4fee-983b-1db896b56c0f)

### To Reproduce

1. Open any hammer map
2. Place a `comp_vactube_junction` entity
3. Change its "Type" parameter to anything except "Straight/Scanner"
4. Observe bug

### Issue Map

Example VMF: 
[vactube_curve_test.zip](https://github.com/user-attachments/files/18241630/vactube_curve_test.zip)

### Expected Behavior

When I switch the type parameters, the appropriate models appear.

### Operating System

Tested on WIndows 11

**Comment by ozxybox** [comment]
migrated! seems like i must've missed some assets in the new CI setup somehow. thanks for finding this!

**Comment by ozxybox** [comment]
Should now hopefully be fixed! Let me know if it's still broken
