### ISSUE TITLE
Paint on grate

### ISSUE THREAD

**Issue by Konclan** [StrataSource/Portal-2-Community-Edition#246]
Hitting a wall next to grating can cause paint to spread onto a grated surface

**Comment by Luke18033** [comment]
This can also be done with `paintallsurfaces`. I assumed it was a weird thing with that command and didn't bother reporting it, but I guess it can happen normally as well.

**Comment by TeamSpen210** [comment]
In Des we've had to add `%nopaint 1` to all the grating materials, it seems that's no longer implied. Easy solution though.

**Comment by CitadelCore** [comment]
Can someone please give me an example of a specific grating material without %nopaint that works in P2?

**Comment by Luke18033** [comment]
Still an issue
![image](https://user-images.githubusercontent.com/19228201/207248774-525230a7-11e6-4482-8107-65b446bac0b3.png)

**Comment by Luke18033** [comment]
This actually happens in base P2 as well, I think you're just supposed to set `%nopaint` - most of the grate materials do have it set, there are just a few that don't. Not sure if it's still something we should address.
![image](https://user-images.githubusercontent.com/19228201/210192677-b5c8f033-d5f0-49ad-8add-2217153943e7.png)

**Comment by ozxybox** [comment]
Closing, as this happens in base P2 as observed by @vrad-exe. If we find that we want some grates to not be paintable, we can override the base game VMT with `%nopaint`. Otherwise, I'd rather not change the behavior and introduce potential compat issues.
