### ISSUE TITLE
Optimize paintmap memory and turn paint on for all maps

### ISSUE THREAD

**Issue by StefanH-AT** [StrataSource/Portal-2-Community-Edition#249]
Paintmaps currently store the full rgb color instead of the paint index. Changing this can reduce the memory usage more than 3 times!!

If we do this, we can turn paint on for every map

**Comment by BlightedLight** [comment]
We need to look into this further as paintmaps may utilise the alpha channel as well.

**Comment by ozxybox** [comment]
Closing, as this issue has been moved to the internal tracker.
