### ISSUE TITLE
Allow projected walls and tractor beams to be recoloured

### ISSUE THREAD

**Issue by RealityAnomaly** [StrataSource/Portal-2-Community-Edition#286]
- [x] Recolourable tractor beams
- [ ] Recolourable projected walls

Allow both to be recoloured. Should be possible with primarycolour/secondarycolour keyvalues and corresponding I/O inputs.

**Comment by SpyceTewan** [comment]
I add this as a SetColor and ResetColor input.

**Comment by Luke18033** [comment]
Funnels are colorable now, why not light bridges still?

**Comment by ozxybox** [comment]
Closing as duplicate of both #807 and #808 
This was also partially implemented but is incomplete.
