### ISSUE TITLE
fix momentary_rot_button

### ISSUE THREAD

**Issue by Valla-Chan** [StrataSource/Portal-2-Community-Edition#310]
if csgo treats this ent the same way as it works in p2, then it has an issue which causes you to release the button immediately after pressing it, rather than simulating holding down the key to move. please fix this! example: https://gyazo.com/721c74a3985c84f2d36db35d1b4d7c5b

**Comment by Luke18033** [comment]
I think the Portal 2 player just lost the ability to continuously `+use` things, that would need to be reimplemented.
