### ISSUE TITLE
For Custom Campaings: abstract away chapter progress.

### ISSUE THREAD

**Issue by SlawekNowy** [StrataSource/Portal-2-Community-Edition#327]
As detailed in [this](https://developer.valvesoftware.com/wiki/Unlocking_chapters_in_your_mod) page, the best way to update chapters is to modify the game code itself.
Would be nice if it was abstracted away into scripts.

**Comment by SpyceTewan** [comment]
I dont even know how often we need to say that the entire ui will be made from scratch

**Comment by Luke18033** [comment]
Issue is too vague to really be useful, we are going to have a per campaign progress tracking system though
