### ISSUE TITLE
Match the visual animation with it's collision mesh

### ISSUE THREAD

**Issue by DarviL82** [StrataSource/Portal-2-Community-Edition#335]
Basically, when an animation starts, if the collision model gets blocked by a physics object, the visual animation will continue until it ends, but the collision mesh will stop. If this could be fixed by just matching both things would make the game much more realistic _(Let's forget about the collisions of the cube)_

Example:
https://streamable.com/us99tu

**Comment by TeamSpen210** [comment]
That's not a really easy thing to do. The animation is totally independent from the physics shadow that follows it, the latter just moves to the correct location each frame. I suppose you could make it pause the animation if blocked, but that would mean it's still in an incorrect position.

**Comment by L89David** [comment]
Yeah, it indeed looks like something pretty complex to pull off...
