### ISSUE TITLE
Portal placement while on stick paint is still broken

### ISSUE THREAD

**Issue by VertexA115** [StrataSource/Portal-2-Community-Edition#340]
Portal placement still does not reflect your stick position in most cases

**Comment by Luke18033** [comment]
What exactly is wrong here? Seems fine to me.

**Comment by Luke18033** [comment]
Still unsure what this is referring to, but if it's suggesting that placing a portal from a wall should place it sideways and the like, I don't think we should do that. It usually just ends up leading to adhesion gel puzzles becoming "get to the right surface to fire a portal in this specific orientation" like in that second adhesion map on the workshop. Given that our adhesion gel is a proper implementation that can be used alongside all the other test elements, I don't think we should rely on gimmicky portal orientation mechanics like this.

**Comment by Luke18033** [comment]
This issue is way too vague to be helpful, if it was referring to the fact that adhesion gel doesn't affect portal orientations then that's not a bug
