### ISSUE TITLE
Feature: entity timescale input

### ISSUE THREAD

**Issue by Konclan** [StrataSource/Portal-2-Community-Edition#505]
## Which component should be improved?
Entities and Timescale

## Describe your suggestion
Allow entities to have their own timescale set by inputs. This could allow control of objects being slowed down or sped up individually instead of changing the game speed.

> Please don't give vague suggestions like "Make button look better" or "Add entity that damages the player".
> Think, how does it work. What are the inputs. What is the expected outcome?
> Please discuss your request on [Discord](https://discord.gg/NcHSmgb) before submitting an issue!

## Expected result
When you fire "SetTimeScale 0.5" on an entity, only it will move at half game speed.

**Comment by ozxybox** [comment]
I have tagged this as "frozen" and "Priority 5" for the time being, as I'm unsure of the implications of slowing down an entity. Slowing down animations would be trivial, maybe even physics could be easy-ish, but slowing down logic I'm unsure of.
This is a super fun idea, but needs more investigation at a later date.

**Comment by ozxybox** [comment]
Closing as out of scope. This would be difficult to properly implement, but could be faked in different ways
