### ISSUE TITLE
fix npc_securitycamera freezing in place

### ISSUE THREAD

**Issue by Fennecai** [StrataSource/Portal-2-Community-Edition#51]
when npc_securitycamera is deactivated; it should revert to looking down, instead of just freezing at the position it was already in.

**Comment by Luke18033** [comment]
It now lowers down, although the angles it moves to seem to weirdly vary depending on the camera entity's orientation:
![chaos_dCCv6Bpi8S](https://user-images.githubusercontent.com/19228201/167332424-9b2d7cfa-8918-4142-9949-be7bca05fd05.png)
![chaos_M5orXK6jk1](https://user-images.githubusercontent.com/19228201/167332430-b71bd255-5132-4a12-99c8-b8c16d8b1b8f.png)
![chaos_66WGnAc1v8](https://user-images.githubusercontent.com/19228201/167332433-999c5d38-3743-4500-bc27-455c9450738b.png)
![chaos_KFdiZWiltp](https://user-images.githubusercontent.com/19228201/167332436-88ffa2e1-f9a5-4c03-9eeb-30dafbb084f8.png)
