### ISSUE TITLE
Playvideo commands need FCVAR_SERVER_CAN_EXECUTE flag

### ISSUE THREAD

**Issue by DanielBatesJ** [StrataSource/Portal-2-Community-Edition#553]
### Describe the bug
Calibration video doesn’t play for orange when starting the calibration course in Cooperative.

### To Reproduce
1. Reset Cooperative Progress (`mp_mark_all_maps_incomplete`)
2. `changelevel mp_coop_calibration` into calibration and take note of how orange has no video playing

### Expected behavior
Player 2 should be able to see the calibration video, and thus be able to skip with `stopvideos`

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows.

**Comment by Luke18033** [comment]
This would likely extend to all videos for all MP players other than the listen server host, needs further testing

**Comment by Luke18033** [comment]
Seems to be a `FCVAR_SERVER_CAN_EXECUTE` issue, console prints this
```
FCVAR_SERVER_CAN_EXECUTE prevented server running command: playvideo_exitcommand_nointerrupt coop_outro end_movie vault-movie_outro
```

**Comment by Luke18033** [comment]
All the `playvideo` commands need the `FCVAR_SERVER_CAN_EXECUTE` flag, currently only `playvideo_end_level_transition` (used for the loading screen videos) has it

**Comment by JJL772** [comment]
Fixed in latest
