### ISSUE TITLE
Bug: Cooperative Lobby Doors do not open correctly

### ISSUE THREAD

**Issue by DanielBatesJ** [StrataSource/Portal-2-Community-Edition#557]
### Describe the bug
Coop lobby doors will not open immediately when you approach them.

### To Reproduce
1. Load into the hub/lobby in cooperative.
2. Go up to a door
3. Leave the immediate area
4. The door will now open

### Expected behavior
Doors open when you approach them.

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows.

**Comment by Luke18033** [comment]
Seems fixed
