### ISSUE TITLE
Bug: `mp_coop_fan` Trigger Hurt

### ISSUE THREAD

**Issue by DanielBatesJ** [StrataSource/Portal-2-Community-Edition#564]
### Describe the bug
`mp_coop_fan` trigger hurt does not turn off after deactivating the fan with the laser.

### To Reproduce
1. Load into `mp_coop_fan`
2. Stop the fan's movement with the laser
3. Fling into the fan

### Expected behavior
Stopping the fan with the laser cube should stop the trigger hurt, and prevent death.

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows.

**Comment by SpyceTewan** [comment]
Is this a map bug? What does this have to do with the engine?

**Comment by DanielBatesJ** [comment]
Assuming the maps are unchanged from base Portal 2 it would have to be an issue with the engine in someway. I could be assuming incorrectly, but that was my assumption.

**Comment by AWildErin** [comment]
I can't seem to replicate this bug at all, the `trigger_hurt` seems to disable just fine?

**Comment by FrozenDragon0** [comment]
@AWildErin The bug still occurs on my end.

**Comment by Luke18033** [comment]
Didn't happen when we played this map in multiplayer the other day

**Comment by Luke18033** [comment]
Seems fixed (tested using two game instances on a LAN server, and online a couple months ago)
