### ISSUE TITLE
Bug: Coop Players are not Crushed While Inside of Portals

### ISSUE THREAD

**Issue by DanielBatesJ** [StrataSource/Portal-2-Community-Edition#567]
### Describe the bug
Being inside of a portal prevents the player in coop from being crushed as expected.

### To Reproduce
1. Load into `mp_coop_rat_maze`
2. Get to the end of the maze, and place a portal to stand in
3. Stand inside the portal while the other player moves off the button.

### Expected behavior
The player should be crushed.

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows

**Comment by EchoesForeAndAft** [comment]
Tested in split-screen, crushing worked as intended.

**Comment by Luke18033** [comment]
Seems fixed (tested using two game instances on a LAN server)

https://user-images.githubusercontent.com/19228201/231053148-62fb82b8-3ae5-4274-80f4-522bdc7f1bd8.mp4
