### ISSUE TITLE
save arbitrary string / number/ etc. variables globally

### ISSUE THREAD

**Issue by Fennecai** [StrataSource/Portal-2-Community-Edition#57]
summary:
![image](https://user-images.githubusercontent.com/10889213/84518715-56cf9680-ac8e-11ea-9f95-73c2530a1ba5.png)

the original way I described the idea:

it would be great if maps could save arbitrary numbers, strings, etc. to .txt or .json files per-mod in a data folder or something, and also load those values back in.

some potential use cases:
* mods to be able to do things such as branching non-linear stories where you have multiple paths, and some of those paths require you to for example activate a button in one map and then go through a door that is now open in a previous map because of that. (save a "this door is open" boolean, load it in the other map to fire an "open" output if true)
* keeping track of collectibles or achievement-ish things, such as finding a trophy in every map or doing tasks that you get rewards for in a hub (save an int value and load it in order to count it; save booleans for the tasks and load them to check what the player could be rewarded with in the hub map)
* being able to enter the same map from multiple different entrances, from other maps (save which map you came from before loading the next map, load that value in the next map- depending on value, teleport player to the corresponding entrance)
* playtesting data being gathered (save data on how much time was spent in a map, etc.)
* keep score in a "minigame" style map, such as a time-trial gel race (like the gelocity time-trial maps) or similar, allowing players to keep track of their score in a particular map.
* characters being aware of a player's previous actions in order to change their voice lines later in a mod (save a boolean of "chell didn't catch Wheatley", if it's loaded and is true later, Wheatley gets angry that chell never caught him)
* multiple maps branching out from a hub, which all have a bearing on the hub in some way (must power on sectors of the facility to unlock other areas of the hub, for example)
* and probably many more which I can't think of myself

this might be implemented via a custom in-hammer entity (or whatever this new branch's equivalent will be) that has save/load inputs with parameters on what key/value to save/load.

I would call it logic_save_value. :)

to clarify: this wouldn't be used in workshop maps; only mods. the data could not be accessed or written to anywhere other than the specific place within the mod's folder itself..i am not in any way suggesting a system to read/write arbitrarily to and from anywhere on the hard-drive, I'm not stupid like that. when i say "arbitrary" i simply mean you can save whatever you want and arent restricted to only saving specific things- like for example in hl2 where you can ONLY save the status of antlion friendliness. I'm suggesting a feature to be able to save the variable state of anything in-game that you want, and then load that data (and ONLY that data) later in another map. like below:

-folder, name: series name
       -map
       -map
       -map
       -config.cfg (contains series info)
       -data.json (contains series global variables, optional)

**Comment by ENDERZOMBI102** [comment]
You stealed my ideas1!!1! Jokes apart, this is really useful

**Comment by Luke18033** [comment]
This is going to be handled through scripting, not an entity. The level transition related examples given could also just be accomplished using HL2 style level transitions.
