### ISSUE TITLE
Bug: Gravity Gun can't punt weighted cubes when holding them

### ISSUE THREAD

**Issue by JJL772** [StrataSource/Portal-2-Community-Edition#573]
### Describe the bug

The gravity gun can't punt weighted cubes when holding them. I only tested weighted cubes

### To Reproduce
1. Open map
2. Give yourself gravity gun
3. Spawn weighted cube
4. Pick up cube with gravity gun
5. Try to punt the cube while holding it

### Expected behavior

Should work just like HL2's gravity gun

**Comment by piotrek94692** [comment]
Doesn't work on any other props too, I have tested on a CS:S bottle, and a HL2 wooden crate.

**Comment by JJL772** [comment]
Yep, this will require some refactoring to the grab controllers. The gravity gun has plenty of other fun bugs too lol

**Comment by Equalizer5118** [comment]
I have found new information about this, the punt force actually scales with the mass of the object. For example, this drawer prop with a mass of 30 gets punted a short distance:
![unknown_2023 02 04-11 42-min](https://user-images.githubusercontent.com/113145248/216786926-0cab4082-81ff-4206-ab94-7a350796fae9.gif)
While Breen's desk, which has a mass of 200, gets punted a longer distance:
![Portal 2 Community Edition_2023 02 04-11 50-min](https://user-images.githubusercontent.com/113145248/216787029-6462590b-3a00-47ff-a7fe-892b75a0e10c.gif)

Unsure how or if this will help, but it seems like its important.

**Comment by JJL772** [comment]
Fixed a couple months ago
