### ISSUE TITLE
Bug: Burning turrets in online coop sometimes crashes the game

### ISSUE THREAD

**Issue by FrozenDragon0** [StrataSource/Portal-2-Community-Edition#622]
### Describe the bug
When burning turrets with lasers in online coop the game will sometimes crash for both players.

### To Reproduce
No Idea what causes this crash, it seems to sometimes happen randomly.

### Expected behavior
Turrets should be exploding normally without the game sometimes crashing.

### Operating System (Optional: Only if OS Specific)
 - OS: Windows

**Comment by Luke18033** [comment]
Was this on a specific map? Couldn't reproduce it on `mp_coop_laser_2`.

**Comment by FrozenDragon0** [comment]
> Was this on a specific map? Couldn't reproduce it on `mp_coop_laser_2`.

Nope, this just happened randomly on the first Art therapy map whilst solving the puzzle and trying to find bugs at the time.

**Comment by Luke18033** [comment]
Probably doesn't happen anymore, there were a lot of weird one-off crashes in early p2ce
