### ISSUE TITLE
Feature: Add autocomplete to npc_create command

### ISSUE THREAD

**Issue by craftablescience** [StrataSource/Portal-2-Community-Edition#626]
## Which component should be improved?
Console

## Describe your suggestion
`ent_create` already has autocomplete, but `npc_create` still does not. It would be nice if this command could have autocomplete, because sometimes the user just wants to spawn an NPC, not any other entity.

## Expected result
`npc_create` has an autocompleted list of available NPCs to spawn.

**Comment by JJL772** [comment]
We could look into doing this. It'd be amazing for testing actually.
