### ISSUE TITLE
Fix prop_portal Start Active keyvalue

### ISSUE THREAD

**Issue by vrad-exe** [StrataSource/Portal-2-Community-Edition#650]
### Describe the bug
If a `prop_portal` is set to start active, it will appear at the world origin regardless of whether it's placed on a valid surface.

### To Reproduce
1. Place `prop_portal` on a valid surface, and set it to start active
2. Compile and load map
3. `prop_portal` is at the origin

### Expected behavior
The portal should appear where it is placed, as long as the surface is valid.

**Comment by craftablescience** [comment]
Closing in favor of #965, this issue came first but the new one has more info and a sample map
