### ISSUE TITLE
Feature: Fix prop_glados_core

### ISSUE THREAD

**Issue by KaziPlays** [StrataSource/Portal-2-Community-Edition#661]
prop_glados_core is an entity used in P1 that appears broken in Portal 2.

I've heard you're trying to create backwards compatibility with P1, so, this would be a good entity to fix.

Also I've heard of a friend that is making a mod for Portal 2 that is P1 styled, this would really help them by allowing prop_glados_core.

**Comment by distributivgesetz** [comment]
- [ ] Reimport all sounds from Portal 1 into P2CE (under `sound/vo/aperture_ai/escape_02_sphere*`)
- [ ] Add all models and textures for original personality cores back (probably `props_bts/glados_ball`)
- [ ] (Optional) Support for custom personality sphere VOs and models

**Comment by AWildErin** [comment]
Sorta forgot this issue exists. I have fixed it to be inline with the P1 entity now, though none of the content has been imported into P2CE. A custom model can be used, VOs are still hard coded

**Comment by Luke18033** [comment]
This is implemented in code, probably open a separate issue for custom voices
