### ISSUE TITLE
Feature: Fire portal gun underwater and place portal unerwater CVar

### ISSUE THREAD

**Issue by Trico-Everfire** [StrataSource/Portal-2-Community-Edition#696]
### Which component should be improved?

Gameplay

### Describe your suggestion

the ability to fire the portal gun underwater and the ability to place portals under water. preferably a CVar.

### Expected result

the ability to fire the portal gun underwater and the ability to place portals under water. preferably a CVar.

**Comment by MyGamepedia** [comment]
Just want to note that this would cause issues like this.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/4dabfb5c-0034-47b1-9759-0e9bee1b21d0

This is why Valve fixed ability to place portals in water for Portal 2.

**Comment by ozxybox** [comment]
Closing as wontfix, as I don't see us implementing this. It sounds like something that would get fairly little use and would potentially cause more issues than it's worth
