### ISSUE TITLE
Models compiled with Portal 2 specifically appear invisible in P2:CE

### ISSUE THREAD

**Issue by FrozenDragon0** [StrataSource/Portal-2-Community-Edition#732]
### Describe the bug

Pretty self explanatory, any models that are compiled in Crowbar specifically for Portal 2 appear invisible in P2:CE when it should be appearing.

This custom model here: https://gamebanana.com/mods/242240 appears fine in normal Portal 2 but when ported over to P2:CE this occurs: 

![unknown](https://user-images.githubusercontent.com/18079316/134929091-ae736e24-ae2c-4d96-bfcb-a82014a2a9b7.png)

### To Reproduce

This may not happen with all models, you may need to test models to see if they appear or not in P2:CE but the model mentioned in the link above is definitely affected by this bug.

### Expected Behavior

The model should work in P2:CE regardless if it's compiled in crowbar specifically for Portal 2 backwards compatibility.

**Comment by JJL772** [comment]
Is this still an issue? We fixed some stuff with models over the last couple years.

**Comment by ozxybox** [comment]
Looking at the asset files, it seems like this was another case of a `.dx90.vtx` file getting mapped up to `.vtx`. Closing, as this was fixed.
