### ISSUE TITLE
Bug: Missing loading plate (portal 2 logo) missing during loading

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [StrataSource/Portal-2-Community-Edition#743]
### Describe the bug

Has the title suggest the loading plate is missing in p2ce the vtf file (loading_plate in hl2 and in portal 2 portal2_logo) don't seem to be draw, this is a bug in the csgo engine where valve accidentally remove it

### To Reproduce

1. Open the game
2. watch the loading screen

### Expected Behavior

The loading plate (portal 2 logo in p2ce) should be displayed during that moment

### Operating System

Windows/Linux

**Comment by bltech** [comment]
This was intentionally removed by Valve, so it's not really a bug

**Comment by Luke18033** [comment]
If this is re-added it needs to be customizable through some config file, since the splash screen doesn't use Panorama.

**Comment by ozxybox** [comment]
Closing as a wontfix. If a particular mod needs the icon back for some reason or another, they can open an issue requesting it.
