### ISSUE TITLE
Fix Exploding Futbol Variant

### ISSUE THREAD

**Issue by KaziPlays** [StrataSource/Portal-2-Community-Edition#774]
### Which component should be improved?

Entity

### Describe your suggestion

Exploding Futbols in P2 are the bombs from the campaign, but those don't act like regular Futbols.

They can't be picked up or thrown.

### Expected result

I think it should have a separate entity for the bombs and the Exploding Futbols as an actual Futbol.

Here's some pictures of it.

![images (76)](https://user-images.githubusercontent.com/72144613/146063838-db4c2682-757b-443c-892f-b56f3c681d72.jpeg)

This is the unused Futbol skin.

![images (75)](https://user-images.githubusercontent.com/72144613/146063910-c164231d-fa4e-46ab-8b56-81354c975e02.jpeg)

This is how Exploding Futbols look like in-game.

**Comment by Luke18033** [comment]
Have you looked at `hot_potato`?

**Comment by Luke18033** [comment]
I don't think we're going to implement this, you could probably replicate it with normal futbols and some vscript
