### ISSUE TITLE
Feature: Customize Tractor Beams Further

### ISSUE THREAD

**Issue by ErinRoseWebs69** [StrataSource/Portal-2-Community-Edition#790]
### Which component should be improved?

Entity

### Describe your suggestion

allow for ability to:
-change funnel texture for a specific funnel
-change funnel size (not required, would be nice) (if implemented, an ability to do this dynamically while in-game would be awesome. im willing to make a custom scalable model for this)
-change particles of funnel without doing so manually like BEE has to do
-just in case its not in, change funnel colors. i think thats already added, i dont remember 
-specify portal size the funnel can go through (potentially idk)
-change funnel entry and exit sounds for specific funnel

### Expected result

nearly full customization of the funnel.

**Comment by ozxybox** [comment]
Closing as duplicate of #807
