### ISSUE TITLE
Bug: Controller doesn't work (Xbox 360)

### ISSUE THREAD

**Issue by ShygalCoco** [StrataSource/Portal-2-Community-Edition#824]
### Describe the bug

Controller input (Xbox 360) does not work in P2:CE even though the controller UI icons do appear.

### To Reproduce

Connect an Xbox 360 controller (real or emulated) to Steam and launch P2:CE.

### Operating System

Windows 10

**Comment by JJL772** [comment]
This should work fine with Steam Input.

**Comment by JJL772** [comment]
By default, p2ce should be using X360 controllers through steam input. Not sure when I made that change on steamworks, it may have been after you reported this issue. Would appreciate a re-test of this.

Note: I've run p2ce using my steam controller and on the steam deck, but work fine. But they also both go through steam input

**Comment by Luke18033** [comment]
Should work now as long as you use steam input, that was broken for a while.
