### ISSUE TITLE
Bug: A.I. Disabled in neurotoxin generator map

### ISSUE THREAD

**Issue by ShygalCoco** [StrataSource/Portal-2-Community-Edition#856]
### Describe the bug

A.I. Disabled text appears on screen and stops Wheatley from talking in neurotoxin generator map.
![image](https://user-images.githubusercontent.com/69723642/162040289-100b8419-ac9c-457a-8d49-7a8204f001ae.png)

### Issue Map

sp_a2_bts5

### To Reproduce

Go to sp_a2_bts5 and it should happen immediately.

### Operating System

Windows 10

**Comment by FrozenDragon0** [comment]
Doesn't seem to occur for me, AI plays like normal.

**Comment by AWildErin** [comment]
This does occur but *very* rarely. I've had it happen to me once but I wasn't exactly testing for it then. When I do try and test for it I never seem to encounter it which is a painful experience.

**Comment by whywhywhyw** [comment]
I somehow managed to reproduce this problem in hl2.

**Comment by whywhywhyw** [comment]
occurs in almost all games that use source.

**Comment by tmob03** [comment]
Seems to be fixed on Staging.
