### ISSUE TITLE
Pressing console key while console is open doesn't close it

### ISSUE THREAD

**Issue by vrad-exe** [StrataSource/Portal-2-Community-Edition#860]
### Describe the bug

In the VGUI console, pressing the console key will close the console instead of typing the character. This doesn't work in the Panorama console which makes it really annoying for me to use since this is how I always close the console normally.

### Issue Map

N/A

### To Reproduce

1. Open console
2. Press toggle console key
3. Character is typed instead of closing console

### Operating System

Tested on Windows 10

**Comment by ozxybox** [comment]
Closing, as I believe this was fixed at some point.
