### ISSUE TITLE
Feature: Workshop Support

### ISSUE THREAD

**Issue by JJL772** [StrataSource/Portal-2-Community-Edition#884]
### Which component should be improved?

Workshop

### Describe your suggestion

# Workshop 

This issue is meant to provide a basic outline for workshop support in P2CE. Suggestions for workshop support should be discussed in the comments here (or in github discussions) so they can be added to this issue.

## Mod Format 

Mods will be uploaded to the workshop as directories, not as VPKs. This should help reduce download size during update as it doesn't need to download the full file.

Mods should be mounted on another searchpath such as `WORKSHOP` to avoid security problems. The internal structure will resemble a normal source mod with `models` `materials` `maps` `resource`  etc. Internal changes are likely required for this, as a lot of code pulls files from `GAME` explicitly. 

We'll need to test performance and memory usage with a large number of mods installed/mounted (>100). Not sure how well Source's file system will scale here, we may need to modify it a bit. Scalability isn't a huge concern for the initial implementation though.

Mods should include some metadata specifying their name, author(s), description and maybe dependencies. This should probably be done in an easily editable format like json (with comments), key values or xml. Something with proper array support would be best though.

Mods should be able to specify dependencies in the addon metadata. Ideally this will allow us to completely ignore the steam workshop's "dependency" system (which sucks). The game will automatically download & install missing dependencies unless the user explicitly uninstalled those dependencies from the in-game UI. 

While dependencies can be specified in workshop, this system both only allows querying dependencies (i.e. no automatic subscription or downloading of dependencies), and relies on a connection to steam to operate. This would cause issues such as not being able to disable addons while offline due to needing a connection to query dependencies through. To circumvent these issues, we should force dependency downloads ingame, check for dependency presence (on launch/mount?), and cache dependencies/children somewhere for offline use.

Overview/notes:
* ~~Packed in VPKs~~ Mods don't need to be packed, instead can be uploaded raw to steam.
* Optionally packed in zip files (?)
* Mounted like any other source mod, but on a separate search path
* Metadata (addon.json/kv/xml??)
* Dependencies can be specified in metadata
* Use async file system for addon management as much as possible. 
* Cache dependencies for offline use

Other things we need to think about:
* ~~Max addon file size 4Gb? (For fat32 file systems, which are unfortunately still common) (Only relevant for ZIP files)~~
* ~~Chunked VPKs supported or not?~~
* ~~ZIP file performance!~~
* Overall performance with large numbers of addons. Should we care or not? 

## In-game UI

Related feature requests: ChaosInitiative/p2ce-panorama-ui#31 ChaosInitiative/p2ce-panorama-ui#35 

There should be an in-game UI for the following workshop functions:
* Addon management- Provide a manager to allow users to subscribe/unsubscribe, enable/disable and cleanup their addon lists. Described in ChaosInitiative/p2ce-panorama-ui#31 
* Addon creation- Provide a simple UI to create a template addon somewhere on the user's file system.
* Addon packing/uploading - Provide a UI to allow the user to pack the specified folder and upload it to the workshop. This should also do some basic validity checking to make sure the addon is actually OK to upload.

Console commands to do most of these things should be provided too, as it would make it easier to manage addons for dedicated servers and such.

## Content Sandboxing 

Another thing we need to think about is how to properly sandbox content. The workshop search path should come after all game mounts to avoid disrupting first-party maps and other content. However, mount order will affect how mods override each other's content. 

We could build a dependency graph for each mod and place interdependent mods in the same sandbox so they can use each other's content without interfering with other unrelated mods. 
The problem with this is if a mod is declared as dependent, it will be placed in the same sandbox as the parent mod, which means the parent mod will be able to override content in the dependent. 

This system could extend to the dynamic mounts system so we can load hl2/tf2/whatever maps with the original assets instead of having certain textures/sounds/etc overridden by portal 2 assets.

**This is not required for the initial workshop implementation, can be done later!** 

## External Utilities 

Provide standalone command-line utilities to do the following:
* Create addons
* Pack addons
* Check addon validity
* Upload addons 

In the new tools system we may want to provide a standalone graphical addon manager. There will already be one for standard standalone source mods. 

### Initial Deliverables

* Command line upload utility
* Mounting of downloaded addons
* imgui debug menu for mounted workshop addons

NOTE: For the initial impl, subscriptions can be done through Steam!

### Expanded Functionality

* Enable/disable/unsubscribe from mods via command line
* Metadata

### In-Game UI

* Panorama UI Component for managing addons
* Problems menu
* Addons menu

### Final Implementation (Required by release 1.0)

* Full metadata & dependencies support
* In-game UI must be complete

**Comment by JJL772** [comment]
We've decided to not use VPKs for mods, instead just uploading directories to steamworks, at least for now. This should simplify code and optimize download sizes as only the updated files will be downloaded. Should also make it easier for users to upload mods as they won't need to be packed beforehand (even though that would be done by the upload tool).

**Comment by TheEnderek0** [comment]
For addons I think a good file structure would be something like this

`Portal 2 Community Edition\workshop\[id]\` and then put the resources there, where id is the id of the workshop item

for the gameinfo you would just specify `Game       workshop\[id]`

This would also allow for easy switching (on/off) of the mounted assets

**Comment by JJL772** [comment]
Yeah, that's the plan. We might actually put them in `p2ce/workshop/<name>-<id>` so it's easier to find workshop mods in your install

**Comment by TheEnderek0** [comment]
As for the upload you could make an asset uploader. It would tell the person uploading the assets of what it will look like (the file structure) after download and possibly return errors when the file structure is wrong.

After that the asset uploader can just pack the files into a zip file with a `.p2ce_addon` extension for the game to unpack after downloading.

**Comment by JJL772** [comment]
Steam supports directly uploading entire directories, packing is not necessary and would reduce efficiency. @Smaedd has written a tool to upload new addons.

**Comment by TheEnderek0** [comment]
Ah cool!

**Comment by SP2G50000** [comment]
This is related to workshop support, so I'm leaving it here: Some maps manipulate user configurations, like key bindings. Some maps do this for various reasons, but at the same time it can result in some annoyances for the user, like a workshop map running `unbind all` or [changing adhesion gel color permanently.](https://steamcommunity.com/sharedfiles/filedetails/?id=2871698184)

It might be useful to prevent these situations from happening. An example solution would be having a map-specific config that workshop maps write to, and is then removed when the session ends or when the map unloads. So if a map runs `unbind all`, the bindings are only removed for that session, and the changes are reverted afterwards.
