### ISSUE TITLE
+use can't be held down on entities

### ISSUE THREAD

**Issue by Nanoman2525** [StrataSource/Portal-2-Community-Edition#888]
### Describe the bug

If you try to refill your health or suit power (when either has depleted by some amount), holding **+use** doesn't continuously flow in health or power, rather, it activates and stops right after. Oddly, spamming **+use** seems to make it behave properly.

### Issue Map

All maps

### To Reproduce

1. Have HL2 resources mounted
2. Open any map
3. Give yourself **item_suit** if you don't already have it
3. Spawn in **item_healthcharger** **item_suitcharger**
4. Disable health regeneration jankily through **sv_regeneration_wait_time 99**
3. Damage yourself a considerable amount
4. Hold E on both of the chargers and notice how the refill process stops immediately

### Operating System

Tested on Windows 10

**Comment by ozxybox** [comment]
Closing as #1712 supersedes this issue with more info, a map, and a video
