### ISSUE TITLE
Bug: Entering any prop_vehicle_ entity with flashlight on keeps it on

### ISSUE THREAD

**Issue by Nanoman2525** [StrataSource/Portal-2-Community-Edition#895]
### Describe the bug

If you enter a vehicle with the flashlight on, the game does not turn it off when you enter the vehicle, as it should.

The Airboat's integrated flashlight still works as it should even while the player's flashlight is on.

### Issue Map

All maps.

### To Reproduce

1. Open any map
2. Type in the console **"impulse 100"** to turn on the player flashlight
3. Spawn any vehicle (i.e. prop_vehicle_jeep)
4. Enter the vehicle
5. Flashlight stays on while inside the vehicle

### Operating System

Tested on Windows 10

**Comment by Trico-Everfire** [comment]
Tested and does indeed turn off the flashlight... however it doesn't reset it's "on" state in the console, so doing impulse 100 won't turn it back on the first time, doing it again will turn it back on.

**Comment by danielah05** [comment]
this seems to work properly now as of the latest nightly build
https://user-images.githubusercontent.com/35849198/190881494-5aa61eb7-c2e1-414b-ac5a-717670dabee5.mp4

**Comment by danielah05** [comment]
oops quick correction, it seems like the actual flashlight toggling works but you can no longer enable the flashlight in the airboat

**Comment by Luke18033** [comment]
Seems fixed
