### ISSUE TITLE
Bug: CTRL + Arrow Key inconsistency in the console

### ISSUE THREAD

**Issue by Wolfcl0ck** [StrataSource/Portal-2-Community-Edition#897]
### Describe the bug

What is expected to happen: Holding CTRL + an arrow key should, under desirable conditions, move the typing line to the next open blankspace when using both the left arrow button and the right arrow button.

What is happening: CTRL + left arrow will always move the typing line to the very start of the line, whereas CTRL + right arrow will move by blank space, as expected

### Issue Map

All maps (console bug)

### To Reproduce

1. open console
2. type any command (or just words) that have one or more spaces in them
3. use ctrl + left arrow to attempt to move to the start of the previous word (this is where the bug happens)
4. use ctrl + right arrow to attempt to move to the end of the next word (this is the intended behavior)

**Comment by Konclan** [comment]
Seems to mostly work, however it functions slightly differently than normal.
https://user-images.githubusercontent.com/16567080/178325639-2edd1e8d-689e-4335-bfc3-7aff91d28e43.mp4

https://user-images.githubusercontent.com/16567080/178326197-f7ac2b0a-70a3-4c47-b6bf-e044e02eb437.mp4

Normally it goes to the beginning of the word where currently it goes to the end of the next word.

**Comment by Wolfcl0ck** [comment]
saw that this was reopened. Closing again because it _is_ fixed.
