### ISSUE TITLE
Remove failsafe transition script logic

### ISSUE THREAD

**Issue by vrad-exe** [StrataSource/Portal-2-Community-Edition#909]
### Which component should be improved?

Other

### Describe your suggestion

In Portal 2, if the map name starts with `sp_`, the game will check for a `logic_script` named `@transition_script` on map spawn. If the entity isn't found, it will create a new `logic_script` called `failsafe_transition_script` set to run the transition script used in the Portal 2 singleplayer campaign. The only visible effect this has is automatically giving the player a dual portal gun, but all of the campaign transition logic has actually been loaded in the background.

For custom maps, this functionality is almost completely useless and annoying to work around if you want a custom transition script or none at all. Since the code doesn't check what scripts are actually set on `@transition_script`, a workaround is to create that entity and set it to run your own script or no scripts, but these kinds of hacks shouldn't be necessary to begin with.

In P2CE this behavior should be removed. Any map that uses Valve's elevator instances will include an explicit copy of the script anyway, so this will only break maps which used custom start/end points and relied on this behavior to give a portal gun. Those maps are relatively rare though.

**Comment by TeamSpen210** [comment]
To fully preserve backwards compatibility, the behaviour could be changed to check for P2's bsp versions, since P2CE has various changes via CSGO.

**Comment by Luke18033** [comment]
We thought about doing that, not sure if it's really necessary though - it's not really reasonable for us to maintain 100% backwards compatibility with every existing workshop map, since those won't be playable in P2CE without copying files around anyway it's fair for us to expect the mapper to update and recompile them. Maybe for simple things like this it'd be fine though.

**Comment by ozxybox** [comment]
Fixed by @craftablescience in the next staging build
