### ISSUE TITLE
Bug: Maps will sometimes crash on boot, then will load next boot.

### ISSUE THREAD

**Issue by verygladen** [StrataSource/Portal-2-Community-Edition#971]
### Describe the bug

When sometimes loading a map (in my case a workshop map), the game will crash after a few seconds of loading it. Then next game boot and game boots after that, the map loads without issues.

### Issue Map

Unknown, happens randomly on some maps, here's the map it mostly happens on for me:
[sp_cinema_playground.zip](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/9390221/sp_cinema_playground.zip)

### To Reproduce

1. Open the map linked
2. See the game crash
3. Boot the game again
4. Open the map again
5. See map load

**Comment by ozxybox** [comment]
Closing, as this issue is fairly old and inactive. If you're able to reproduce this, please feel free to open it back up!
