### ISSUE TITLE
Bug: Crash on startup

### ISSUE THREAD

**Issue by DrPeeper228** [StrataSource/Portal-2-Community-Edition#977]
### Describe the bug

when is tart the game it crashes
here is what it says in terminal
veltron@veltron-System-Product-Name:~$ '/media/veltron/d04382c0-2a4a-4894-a407-cd540297aa95/SteamLibrary/steamapps/common/Portal 2 Community Edition/p2ce.sh' 
[S_API] SteamAPI_Init(): Loaded '/home/veltron/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 440000
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198980318640 [API loaded no]
SDL video target is 'x11'
Created D3D11 device successfully
FileSystem_Init::MountGames: Successfully mounted game AppID 620 with 8 subfolders and/or VPKs.
Got ISteamNetworkingSockets user interfaces from steam lib
USRLOCAL path using Steam profile data folder:
/home/veltron/.steam/debian-installation/userdata/1020052912/440000/local
SDL video target is 'x11'
Did not detect any valid joysticks.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Fossilize INFO: Overriding serialization path: "/media/veltron/d04382c0-2a4a-4894-a407-cd540297aa95/SteamLibrary/steamapps/shadercache/440000/fozpipelinesv6/steamapprun_pipeline_cache".
[6505:6505:20220904,103215.259503:ERROR elf_dynamic_array_reader.h:61] tag not found
[6505:6505:20220904,103215.260859:ERROR elf_dynamic_array_reader.h:61] tag not found
[6505:6505:20220904,103215.261979:ERROR elf_dynamic_array_reader.h:61] tag not found
[6505:6505:20220904,103215.264118:ERROR elf_dynamic_array_reader.h:61] tag not found
[6505:6505:20220904,103215.264179:ERROR elf_dynamic_array_reader.h:61] tag not found
Aborted (core dumped)

### Issue Map

its on startup

### To Reproduce

idk, i just launch and .... crash

### Operating System

Linux Ubuntu Desktop 22.04 LTS

**Comment by JJL772** [comment]
Looking at this log, it looks like you're using lavapipe, which is a software renderer. Make sure your GPU supports Vulkan and that you have the necessary drivers installed.

**Comment by ozxybox** [comment]
Closing, as this issue is quite old and inactive.
