### ISSUE TITLE
Bug: Some text using the wrong font in Panorama

### ISSUE THREAD

**Issue by Doclic** [StrataSource/Portal-2-Community-Edition#980]
### Describe the bug

Subtitles, a `game_text`'s text, and the tutorial text all use a Monospace font when using Panorama UI

What it should look like:
![image](https://user-images.githubusercontent.com/30270428/188342200-8f954292-3ae3-4e69-954b-c16f1e6c1700.png)

What it looks like when using Panorama:
![image](https://user-images.githubusercontent.com/30270428/188341934-46a45bc6-3ab9-42a6-bceb-2c6fe5b88b20.png)

### To Reproduce

1. Launch without Panorama
2. Enable subtitles
3. Restart the game with Panorama
4. Get Genetic Lifeform and Disk Operating System to talk or trigger a `game_text`

### Operating System

Tested using Linux (Pop!_OS)

**Comment by Doclic** [comment]
Turns out the `game_text` entity also uses the same font.
I'll make a second issue for `game_text` because it also crashes the game when you're using Panorama UI.

**Comment by ozxybox** [comment]
This is fixed in staging. Thanks Stefan!
